# Generated by Django 4.2.10 on 2024-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('statefp', models.IntegerField()),
                ('intptlat', models.FloatField()),
                ('intptlon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('statefp', models.IntegerField()),
                ('stusps', models.CharField(max_length=2)),
                ('intptlat', models.FloatField()),
                ('intptlon', models.FloatField()),
            ],
        ),
    ]
