# Generated by Django 2.2.19 on 2021-04-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cts_forms', '0106_donotemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tms_id', models.BigIntegerField(unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('inconclusive', 'Inconclusive')], max_length=32)),
                ('report', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cts_forms.Report')),
            ],
        ),
    ]
