# Generated by Django 2.2.24 on 2021-09-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsemail',
            name='purpose',
            field=models.CharField(choices=[('auto', 'Autoresponse'), ('manual', 'Manual response')], default='manual', max_length=32),
        ),
    ]
