# Generated by Django 3.2.17 on 2023-02-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_tmsemail_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsemail',
            name='blah',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
