# Generated by Django 4.2.3 on 2023-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_tmsemail_html_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmsemail',
            name='purpose',
            field=models.CharField(choices=[('auto', 'Autoresponse'), ('manual', 'Manual response'), ('internal', 'Internal notification')], default='manual', max_length=32),
        ),
    ]
