# Generated by Django 4.2.3 on 2024-06-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0208_notificationpreference_saved_searches_and_more'),
        ('tms', '0004_alter_tmsemail_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmsemail',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cts_forms.report'),
        ),
    ]
