# Generated by Django 4.2.2 on 2023-07-18 18:19
import os

from django.db import migrations

from analytics import models


class Migration(migrations.Migration):
    """Create a read-only analytics user with access to postgres tables.

    Only does this in the DEVELOP and LOCAL envs.
    """

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    if os.environ.get('ENV', 'UNDEFINED') in ['LOCAL', 'DEVELOP']:
        operations = models.make_analytics_user()
    else:
        operations = []
