# Generated by Django 4.2.2 on 2023-07-18 18:19
import os

from django.db import migrations
from django.conf import settings

from analytics import models


class Migration(migrations.Migration):
    """Create a read-only analytics user with access to postgres tables.

    Only does this in the DEVELOP and LOCAL envs.
    """

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    if settings.TESTING:
        # The analytics user isn't needed for tests, and having the tests try to create it can break local development.
        operations = []
    elif os.environ.get('ENV', 'UNDEFINED') in ['LOCAL', 'DEVELOP']:
        operations = models.make_analytics_user()
    else:
        operations = []
