# Generated by Django 4.2.3 on 2023-09-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0179_delete_dashboardembed'),
        ('analytics', '0003_alter_analyticsfile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, help_text='A human-readable header for the group', max_length=256)),
                ('order', models.IntegerField(default=0, help_text='The order in which to display this group, lower numbers first')),
            ],
        ),
        migrations.CreateModel(
            name='FileGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.analyticsfile')),
                ('dashboard_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dashboardgroup')),
                ('show_only_for_sections', models.ManyToManyField(blank=True, help_text='If set, the notebook will only be displayed for the given section(s). If unset, the notebook will be displayed for all sections.', to='cts_forms.routingsection')),
            ],
        ),
        migrations.AddField(
            model_name='dashboardgroup',
            name='notebooks',
            field=models.ManyToManyField(blank=True, help_text='The notebooks to display in this group', through='analytics.FileGroupAssignment', to='analytics.analyticsfile'),
        ),
    ]
