# Generated by Django 4.2.11 on 2024-10-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_prod_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsfile',
            name='description',
            field=models.CharField(blank=True, help_text='A description for the notebook', max_length=1024),
        ),
    ]
