# Generated by Django 4.2.11 on 2024-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_analyticsfile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsfile',
            name='description',
            field=models.CharField(blank=True, help_text='A description for the notebook', max_length=1024, null=True),
        ),
    ]
