# Generated by Django 2.2.4 on 2019-09-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cts_forms', '0001_initial'), ('cts_forms', '0002_auto_20190607_1553'), ('cts_forms', '0003_auto_20190804_1538'), ('cts_forms', '0004_auto_20190804_1614'), ('cts_forms', '0005_delete_choice'), ('cts_forms', '0006_auto_20190809_2103'), ('cts_forms', '0007_auto_20190809_2130'), ('cts_forms', '0008_auto_20190810_1426'), ('cts_forms', '0009_auto_20190810_2124'), ('cts_forms', '0010_auto_20190813_2104'), ('cts_forms', '0011_auto_20190813_2121'), ('cts_forms', '0012_auto_20190815_2125'), ('cts_forms', '0013_auto_20190816_1844'), ('cts_forms', '0014_auto_20190816_1845'), ('cts_forms', '0015_auto_20190821_1800'), ('cts_forms', '0016_auto_20190821_1800'), ('cts_forms', '0017_auto_20190821_1800'), ('cts_forms', '0018_auto_20190821_1801'), ('cts_forms', '0019_auto_20190821_1812'), ('cts_forms', '0020_auto_20190821_1816'), ('cts_forms', '0021_auto_20190821_1819'), ('cts_forms', '0022_auto_20190821_1819'), ('cts_forms', '0023_auto_20190821_1823'), ('cts_forms', '0024_auto_20190821_1823'), ('cts_forms', '0025_auto_20190821_1826'), ('cts_forms', '0026_auto_20190821_1924'), ('cts_forms', '0027_auto_20190821_1943'), ('cts_forms', '0028_auto_20190821_1958'), ('cts_forms', '0029_auto_20190821_2016'), ('cts_forms', '0030_auto_20190821_2030'), ('cts_forms', '0031_auto_20190821_2059'), ('cts_forms', '0032_auto_20190821_2105'), ('cts_forms', '0033_auto_20190821_2128'), ('cts_forms', '0034_auto_20190823_1738')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_class', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_complaint', models.CharField(choices=[('denied_access', 'Denied access or removed from a location (including segregation)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against')], default=None, max_length=100)),
                ('place', models.CharField(choices=[('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('place_of_worship', 'Place of worship'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('government_building', 'Another government building (courthouse, DMV, post office)')], default=None, max_length=100)),
                ('public_or_private_employer', models.CharField(choices=[('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True)),
                ('employer_size', models.CharField(choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], default=None, max_length=100, null=True)),
                ('public_or_private_school', models.CharField(choices=[('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True)),
                ('public_or_private_facility', models.CharField(choices=[('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True)),
                ('public_or_private_healthcare', models.CharField(choices=[('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True)),
                ('respondent_type', models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('healthcare', 'Healthcare provider or staff'), ('lender', 'Bank or loaning service')], default=None, max_length=100, null=True)),
                ('respondent_contact_ask', models.BooleanField(null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=225, null=True)),
                ('respondent_city', models.CharField(blank=True, max_length=700, null=True)),
                ('violation_summary', models.TextField()),
                ('when', models.CharField(choices=[('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years'), ('greater_than_3_years', 'More than 3 years ago')], default=None, max_length=700)),
                ('how_many', models.CharField(blank=True, choices=[('no', 'No'), ('not_sure', "I'm not sure"), ('yes', 'Yes')], default=None, max_length=700, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('parent_guardian', 'Im a parent or guardian of the person affected'), ('professional', 'Im providing professional assistance'), ('witness to the situation', 'Im a witness to the situation')], default=None, max_length=100, null=True)),
                ('do_not_contact', models.BooleanField(null=True)),
                ('contact_given_name', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_family_name', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_address_line_1', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_address_line_2', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('protected_class', models.ManyToManyField(blank=True, to='cts_forms.ProtectedClass')),
                ('contact_state', models.CharField(blank=True, choices=[('AL', 'Alabama '), ('AK', 'Alaska '), ('AZ', 'Arizona '), ('AR', 'Arkansas '), ('CA', 'California '), ('CO', 'Colorado '), ('CT', 'Connecticut '), ('DE', 'Delaware '), ('DC', 'District of Columbia '), ('FL', 'Florida '), ('GA', 'Georgia '), ('HI', 'Hawaii '), ('ID', 'Idaho '), ('IL', 'Illinois '), ('IN', 'Indiana '), ('IA', 'Iowa '), ('KS', 'Kansas '), ('KY', 'Kentucky '), ('LA', 'Louisiana '), ('ME', 'Maine '), ('MD', 'Maryland '), ('MA', 'Massachusetts '), ('MI', 'Michigan '), ('MN', 'Minnesota '), ('MS', 'Mississippi '), ('MO', 'Missouri '), ('MT', 'Montana '), ('NE', 'Nebraska '), ('NV', 'Nevada '), ('NH', 'New Hampshire '), ('NJ', 'New Jersey '), ('NM', 'New Mexico '), ('NY', 'New York '), ('NC', 'North Carolina '), ('ND', 'North Dakota '), ('OH', 'Ohio '), ('OK', 'Oklahoma '), ('OR', 'Oregon '), ('PA', 'Pennsylvania '), ('RI', 'Rhode Island '), ('SC', 'South Carolina '), ('SD', 'South Dakota '), ('TN', 'Tennessee '), ('TX', 'Texas '), ('UT', 'Utah '), ('VT', 'Vermont '), ('VA', 'Virginia '), ('WA', 'Washington '), ('WV', 'West Virginia '), ('WI', 'Wisconsin '), ('WY', 'Wyoming '), ('AS', 'American Samoa '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('PR', 'Puerto Rico '), ('VI', 'Virgin Islands '), ('AE', 'Armed Forces Africa '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('AP', 'Armed Forces Pacific ')], max_length=100, null=True)),
                ('respondent_state', models.CharField(blank=True, choices=[('AL', 'Alabama '), ('AK', 'Alaska '), ('AZ', 'Arizona '), ('AR', 'Arkansas '), ('CA', 'California '), ('CO', 'Colorado '), ('CT', 'Connecticut '), ('DE', 'Delaware '), ('DC', 'District of Columbia '), ('FL', 'Florida '), ('GA', 'Georgia '), ('HI', 'Hawaii '), ('ID', 'Idaho '), ('IL', 'Illinois '), ('IN', 'Indiana '), ('IA', 'Iowa '), ('KS', 'Kansas '), ('KY', 'Kentucky '), ('LA', 'Louisiana '), ('ME', 'Maine '), ('MD', 'Maryland '), ('MA', 'Massachusetts '), ('MI', 'Michigan '), ('MN', 'Minnesota '), ('MS', 'Mississippi '), ('MO', 'Missouri '), ('MT', 'Montana '), ('NE', 'Nebraska '), ('NV', 'Nevada '), ('NH', 'New Hampshire '), ('NJ', 'New Jersey '), ('NM', 'New Mexico '), ('NY', 'New York '), ('NC', 'North Carolina '), ('ND', 'North Dakota '), ('OH', 'Ohio '), ('OK', 'Oklahoma '), ('OR', 'Oregon '), ('PA', 'Pennsylvania '), ('RI', 'Rhode Island '), ('SC', 'South Carolina '), ('SD', 'South Dakota '), ('TN', 'Tennessee '), ('TX', 'Texas '), ('UT', 'Utah '), ('VT', 'Vermont '), ('VA', 'Virginia '), ('WA', 'Washington '), ('WV', 'West Virginia '), ('WI', 'Wisconsin '), ('WY', 'Wyoming '), ('AS', 'American Samoa '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('PR', 'Puerto Rico '), ('VI', 'Virgin Islands '), ('AE', 'Armed Forces Africa '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('AP', 'Armed Forces Pacific ')], max_length=100, null=True)),
                ('who_reporting_for', models.CharField(choices=[('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100)),
            ],
        ),
    ]
