# Generated by Django 2.2.4 on 2019-09-24 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0002_auto_20190910_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=225, null=True, validators=[django.core.validators.RegexValidator('^\\D*(\\d\\D*){7,15}$')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(blank=True, choices=[('denied_access', 'Denied access or removed from a location (including segregation)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against')], default=None, max_length=100, null=True),
        ),
    ]
