# Generated by Django 2.2.1 on 2019-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0002_auto_20190607_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='state_or_territory',
        ),
        migrations.RemoveField(
            model_name='violationreport',
            name='state',
        ),
        migrations.AddField(
            model_name='violationreport',
            name='state',
            field=models.ManyToManyField(to='cts_forms.State'),
        ),
    ]
