# Generated by Django 2.2.1 on 2019-08-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0003_auto_20190804_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_or_territory',
            new_name='state_name',
        ),
        migrations.AlterField(
            model_name='violationreport',
            name='state',
            field=models.ManyToManyField(blank=True, null=True, to='cts_forms.State'),
        ),
    ]
