# Generated by Django 2.2.3 on 2019-08-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0004_auto_20190804_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
