# Generated by Django 2.2.4 on 2019-09-25 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0004_auto_20190924_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=225, null=True, validators=[django.core.validators.RegexValidator('^(?=^\\D*(\\d\\D*){7,15}$)(?=^(?:(?![a-zA-Z]).)*$).*$')]),
        ),
    ]
