# Generated by Django 2.2.3 on 2019-08-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0006_auto_20190809_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_address_line_1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_address_line_2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_family_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_given_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(blank=True, choices=[('15_or_more', '15 or more employees'), ('14_or_less', 'Fewer than 15 employees')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('not_sure', "I'm not sure"), ('yes', 'Yes')], max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(blank=True, choices=[('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('place_of_worship', 'Place of worship'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('workplace', 'Workplace or potential workplace'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('vote', 'Ability to vote was impacted'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('discriminated_against', 'Otherwise discriminated against'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('religion', 'Religion'), ('genetic_information', 'Genetic information'), ('age', 'Age'), ('race_color', 'Race/color'), ('national_origin', 'National origin (including ancestry, ethnicity, and language)'), ('immigration_citizenship', 'Immigration or citizenship status (you do not have to divulge your status)'), ('sexual_orientation', 'Sexual orientation'), ('military_status', 'Military status'), ('familial_status', 'Familial, marital, or parental status'), ('disability', 'Disability (including temporary)'), ('sex_gender', 'Sex or gender identity (including pregnancy)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('not_sure', "I'm not sure"), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('another', "I'm reporting on behalf of another person"), ('myself', "I'm reporting for myself"), ('undisclosed', 'I prefer not to disclose')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('healthcare', 'Healthcare provider or staff'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('last_3_years', 'Within the last 3 years'), ('last_6_months', 'Within the last 6 months'), ('greater_than_3_years', 'More than 3 years ago')], max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('healthcare', 'Healthcare provider or staff'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], max_length=100, null=True),
        ),
    ]
