# Generated by Django 2.2.4 on 2019-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0006_auto_20190930_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='violation_summary',
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
    ]
