# Generated by Django 2.2.4 on 2019-10-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0007_auto_20190930_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='other_class',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='protectedclass',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('disability', 'Disability (including temporary or in recovery)'), ('race', 'Race/color'), ('origin', 'National origin (including ancestry, ethnicity, and language)'), ('immigration', 'Immigration/citizenship status (choosing this does not share your status)'), ('religion', 'Religion'), ('gender', 'Sex, gender identity, or pregnancy'), ('orientation', 'Sexual orientation'), ('family', 'Familial, marital, or parental status'), ('military', 'Military status'), ('age', 'Age'), ('genetic', 'Genetic information'), ('other', 'Other')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('home', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('place_of_worship', 'Place of worship'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('government_building', 'Another government building (courthouse, DMV, post office)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='protected_class',
            field=models.ManyToManyField(to='cts_forms.ProtectedClass'),
        ),
    ]
