# Generated by Django 2.2.3 on 2019-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0007_auto_20190809_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact_state',
        ),
        migrations.AddField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('DC', 'District of Columbia '), ('MS', 'Mississippi '), ('PR', 'Puerto Rico '), ('AE', 'Armed Forces Europe '), ('NE', 'Nebraska '), ('ID', 'Idaho '), ('AP', 'Armed Forces Pacific '), ('WI', 'Wisconsin '), ('AR', 'Arkansas '), ('WA', 'Washington '), ('MP', 'Northern Mariana Islands '), ('AZ', 'Arizona '), ('AE', 'Armed Forces Africa '), ('NH', 'New Hampshire '), ('ND', 'North Dakota '), ('RI', 'Rhode Island '), ('AA', 'Armed Forces Americas '), ('NY', 'New York '), ('AK', 'Alaska '), ('SD', 'South Dakota '), ('NC', 'North Carolina '), ('MT', 'Montana '), ('NJ', 'New Jersey '), ('IN', 'Indiana '), ('SC', 'South Carolina '), ('IA', 'Iowa '), ('MI', 'Michigan '), ('AS', 'American Samoa '), ('MD', 'Maryland '), ('VI', 'Virgin Islands '), ('IL', 'Illinois '), ('LA', 'Louisiana '), ('KY', 'Kentucky '), ('MA', 'Massachusetts '), ('OK', 'Oklahoma '), ('OH', 'Ohio '), ('UT', 'Utah '), ('WY', 'Wyoming '), ('TX', 'Texas '), ('CT', 'Connecticut '), ('NM', 'New Mexico '), ('FL', 'Florida '), ('DE', 'Delaware '), ('VA', 'Virginia '), ('GU', 'Guam '), ('CA', 'California '), ('KS', 'Kansas '), ('OR', 'Oregon '), ('AE', 'Armed Forces Canada '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Middle East '), ('WV', 'West Virginia '), ('VT', 'Vermont '), ('AL', 'Alabama '), ('HI', 'Hawaii '), ('NV', 'Nevada '), ('GA', 'Georgia '), ('ME', 'Maine '), ('CO', 'Colorado '), ('MN', 'Minnesota '), ('PA', 'Pennsylvania '), ('MO', 'Missouri ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(blank=True, choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('not_sure', "I'm not sure"), ('no', 'No'), ('yes', 'Yes')], max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(blank=True, choices=[('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('place_of_worship', 'Place of worship'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('workplace', 'Workplace or potential workplace'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_housing', 'Denied housing or subjected to harmful living conditions')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('age', 'Age'), ('military_status', 'Military status'), ('genetic_information', 'Genetic information'), ('familial_status', 'Familial, marital, or parental status'), ('immigration_citizenship', 'Immigration or citizenship status (you do not have to divulge your status)'), ('religion', 'Religion'), ('sexual_orientation', 'Sexual orientation'), ('sex_gender', 'Sex or gender identity (including pregnancy)'), ('national_origin', 'National origin (including ancestry, ethnicity, and language)'), ('disability', 'Disability (including temporary)'), ('race_color', 'Race/color')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility'), ('not_sure', 'Not sure'), ('federal_facility', 'Federal facility')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility'), ('not_sure', 'Not sure'), ('federal_facility', 'Federal facility')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(blank=True, choices=[('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('not_sure', "I'm not sure"), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='report',
            name='respondent_state',
        ),
        migrations.AddField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('DC', 'District of Columbia '), ('MS', 'Mississippi '), ('PR', 'Puerto Rico '), ('AE', 'Armed Forces Europe '), ('NE', 'Nebraska '), ('ID', 'Idaho '), ('AP', 'Armed Forces Pacific '), ('WI', 'Wisconsin '), ('AR', 'Arkansas '), ('WA', 'Washington '), ('MP', 'Northern Mariana Islands '), ('AZ', 'Arizona '), ('AE', 'Armed Forces Africa '), ('NH', 'New Hampshire '), ('ND', 'North Dakota '), ('RI', 'Rhode Island '), ('AA', 'Armed Forces Americas '), ('NY', 'New York '), ('AK', 'Alaska '), ('SD', 'South Dakota '), ('NC', 'North Carolina '), ('MT', 'Montana '), ('NJ', 'New Jersey '), ('IN', 'Indiana '), ('SC', 'South Carolina '), ('IA', 'Iowa '), ('MI', 'Michigan '), ('AS', 'American Samoa '), ('MD', 'Maryland '), ('VI', 'Virgin Islands '), ('IL', 'Illinois '), ('LA', 'Louisiana '), ('KY', 'Kentucky '), ('MA', 'Massachusetts '), ('OK', 'Oklahoma '), ('OH', 'Ohio '), ('UT', 'Utah '), ('WY', 'Wyoming '), ('TX', 'Texas '), ('CT', 'Connecticut '), ('NM', 'New Mexico '), ('FL', 'Florida '), ('DE', 'Delaware '), ('VA', 'Virginia '), ('GU', 'Guam '), ('CA', 'California '), ('KS', 'Kansas '), ('OR', 'Oregon '), ('AE', 'Armed Forces Canada '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Middle East '), ('WV', 'West Virginia '), ('VT', 'Vermont '), ('AL', 'Alabama '), ('HI', 'Hawaii '), ('NV', 'Nevada '), ('GA', 'Georgia '), ('ME', 'Maine '), ('CO', 'Colorado '), ('MN', 'Minnesota '), ('PA', 'Pennsylvania '), ('MO', 'Missouri ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('landlord', 'Landlord, leasing office, or home/rental provider'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years')], max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('landlord', 'Landlord, leasing office, or home/rental provider'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
