# Generated by Django 2.2.4 on 2019-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0008_auto_20191009_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherclass',
            name='other_class',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
