# Generated by Django 2.2.4 on 2019-10-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0008_auto_20191011_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedclass',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('disability', 'Disability (including temporary or in recovery)'), ('race', 'Race/color'), ('origin', 'National origin (including ancestry, ethnicity, and language)'), ('immigration', 'Immigration/citizenship status (choosing this does not share your status)'), ('religion', 'Religion'), ('gender', 'Sex or gender identity (including gender stereotypes) or pregnancy'), ('orientation', 'Sexual orientation'), ('family', 'Family, marriage, or parental status'), ('military', 'Military status'), ('age', 'Age'), ('genetic', 'Genetic information'), ('other', 'Other')], max_length=100, null=True, unique=True),
        ),
    ]
