# Generated by Django 2.2.3 on 2019-08-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0008_auto_20190810_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_class', models.CharField(blank=True, choices=[('genetic_information', 'Genetic information'), ('race_color', 'Race/color'), ('disability', 'Disability (including temporary)'), ('familial_status', 'Familial, marital, or parental status'), ('religion', 'Religion'), ('immigration_citizenship', 'Immigration or citizenship status (you do not have to divulge your status)'), ('sex_gender', 'Sex or gender identity (including pregnancy)'), ('military_status', 'Military status'), ('age', 'Age'), ('national_origin', 'National origin (including ancestry, ethnicity, and language)'), ('sexual_orientation', 'Sexual orientation')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatesAndTerritories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_territory', models.CharField(blank=True, choices=[('SC', 'South Carolina '), ('ND', 'North Dakota '), ('AL', 'Alabama '), ('CO', 'Colorado '), ('VT', 'Vermont '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Africa '), ('NM', 'New Mexico '), ('SD', 'South Dakota '), ('AS', 'American Samoa '), ('PR', 'Puerto Rico '), ('MP', 'Northern Mariana Islands '), ('MD', 'Maryland '), ('HI', 'Hawaii '), ('DC', 'District of Columbia '), ('AK', 'Alaska '), ('KS', 'Kansas '), ('NY', 'New York '), ('WA', 'Washington '), ('ME', 'Maine '), ('MA', 'Massachusetts '), ('VI', 'Virgin Islands '), ('AZ', 'Arizona '), ('DE', 'Delaware '), ('NH', 'New Hampshire '), ('ID', 'Idaho '), ('LA', 'Louisiana '), ('MT', 'Montana '), ('MS', 'Mississippi '), ('NJ', 'New Jersey '), ('PA', 'Pennsylvania '), ('RI', 'Rhode Island '), ('UT', 'Utah '), ('AP', 'Armed Forces Pacific '), ('KY', 'Kentucky '), ('VA', 'Virginia '), ('CA', 'California '), ('IA', 'Iowa '), ('TX', 'Texas '), ('AR', 'Arkansas '), ('WV', 'West Virginia '), ('IN', 'Indiana '), ('WI', 'Wisconsin '), ('AE', 'Armed Forces Europe '), ('MI', 'Michigan '), ('AE', 'Armed Forces Canada '), ('GU', 'Guam '), ('IL', 'Illinois '), ('NE', 'Nebraska '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Middle East '), ('GA', 'Georgia '), ('OH', 'Ohio '), ('NC', 'North Carolina '), ('OR', 'Oregon '), ('CT', 'Connecticut '), ('MO', 'Missouri '), ('WY', 'Wyoming '), ('OK', 'Oklahoma '), ('FL', 'Florida '), ('NV', 'Nevada '), ('MN', 'Minnesota ')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='contact_state',
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', "I'm not sure")], max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(blank=True, choices=[('government_building', 'Another government building (courthouse, DMV, post office)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('place_of_worship', 'Place of worship'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('voting', 'Voting location or ballot (including mail-in ballots)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('denied_access', 'Denied access or removed from a location (including segregation)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='report',
            name='protected_class',
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('not_sure', "I'm not sure"), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(blank=True, choices=[('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('not_sure', "I'm not sure")], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose'), ('myself', "I'm reporting for myself")], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='report',
            name='respondent_state',
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years'), ('greater_than_3_years', 'More than 3 years ago')], max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_state',
            field=models.ManyToManyField(null=True, related_name='contact_state', to='cts_forms.StatesAndTerritories'),
        ),
        migrations.AddField(
            model_name='report',
            name='protected_class',
            field=models.ManyToManyField(blank=True, to='cts_forms.ProtectedClass'),
        ),
        migrations.AddField(
            model_name='report',
            name='respondent_state',
            field=models.ManyToManyField(null=True, related_name='respondent_state', to='cts_forms.StatesAndTerritories'),
        ),
    ]
