# Generated by Django 2.2.3 on 2019-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0009_auto_20190810_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedclass',
            name='protected_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.ManyToManyField(blank=True, related_name='contact_state', to='cts_forms.StatesAndTerritories'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(blank=True, choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('not_sure', "I'm not sure"), ('yes', 'Yes'), ('no', 'No')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(blank=True, choices=[('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('place_of_worship', 'Place of worship'), ('workplace', 'Workplace or potential workplace'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('denied_access', 'Denied access or removed from a location (including segregation)'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('vote', 'Ability to vote was impacted'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('discriminated_against', 'Otherwise discriminated against'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('not_sure', "I'm not sure"), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(blank=True, choices=[('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('undisclosed', 'I prefer not to disclose'), ('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.ManyToManyField(blank=True, related_name='respondent_state', to='cts_forms.StatesAndTerritories'),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('healthcare', 'Healthcare provider or staff'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('lender', 'Bank or loaning service'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('employer', 'Employer or potential employer'), ('healthcare', 'Healthcare provider or staff'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('lender', 'Bank or loaning service'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statesandterritories',
            name='state_territory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
