# Generated by Django 2.2.4 on 2019-10-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0009_auto_20191009_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='other_class',
        ),
        migrations.AddField(
            model_name='report',
            name='other_class',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='OtherClass',
        ),
    ]
