# Generated by Django 2.2.3 on 2019-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0010_auto_20190813_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(blank=True, choices=[('15_or_more', '15 or more employees'), ('14_or_less', 'Fewer than 15 employees')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('not_sure', "I'm not sure"), ('yes', 'Yes')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(blank=True, choices=[('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('place_of_worship', 'Place of worship'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('government_building', 'Another government building (courthouse, DMV, post office)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('discriminated_against', 'Otherwise discriminated against'), ('prevented_from_service', 'Prevented from using a service or service terminated')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure"), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(blank=True, choices=[('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('not_sure', "I'm not sure"), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('healthcare', 'Healthcare provider or staff'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('lender', 'Bank or loaning service')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years'), ('last_6_months', 'Within the last 6 months')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('lender', 'Bank or loaning service'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], max_length=100, null=True),
        ),
    ]
