# Generated by Django 2.2.4 on 2019-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0010_auto_20191009_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='other_class',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
