# Generated by Django 2.2.3 on 2019-08-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0011_auto_20190813_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact_state',
        ),
        migrations.AddField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('NJ', 'New Jersey '), ('OK', 'Oklahoma '), ('SC', 'South Carolina '), ('ND', 'North Dakota '), ('CA', 'California '), ('NC', 'North Carolina '), ('DC', 'District of Columbia '), ('VA', 'Virginia '), ('VI', 'Virgin Islands '), ('CT', 'Connecticut '), ('IN', 'Indiana '), ('KS', 'Kansas '), ('GA', 'Georgia '), ('CO', 'Colorado '), ('AZ', 'Arizona '), ('TX', 'Texas '), ('NV', 'Nevada '), ('LA', 'Louisiana '), ('DE', 'Delaware '), ('NE', 'Nebraska '), ('AK', 'Alaska '), ('IL', 'Illinois '), ('AE', 'Armed Forces Africa '), ('PA', 'Pennsylvania '), ('AA', 'Armed Forces Americas '), ('HI', 'Hawaii '), ('WI', 'Wisconsin '), ('TN', 'Tennessee '), ('WY', 'Wyoming '), ('SD', 'South Dakota '), ('PR', 'Puerto Rico '), ('AE', 'Armed Forces Europe '), ('MD', 'Maryland '), ('NH', 'New Hampshire '), ('VT', 'Vermont '), ('ME', 'Maine '), ('NM', 'New Mexico '), ('OH', 'Ohio '), ('UT', 'Utah '), ('AL', 'Alabama '), ('NY', 'New York '), ('KY', 'Kentucky '), ('AR', 'Arkansas '), ('MI', 'Michigan '), ('AE', 'Armed Forces Canada '), ('MO', 'Missouri '), ('MS', 'Mississippi '), ('WV', 'West Virginia '), ('ID', 'Idaho '), ('IA', 'Iowa '), ('MN', 'Minnesota '), ('RI', 'Rhode Island '), ('GU', 'Guam '), ('AS', 'American Samoa '), ('FL', 'Florida '), ('MT', 'Montana '), ('MP', 'Northern Mariana Islands '), ('MA', 'Massachusetts '), ('AP', 'Armed Forces Pacific '), ('WA', 'Washington '), ('AE', 'Armed Forces Middle East '), ('OR', 'Oregon ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('not_sure', "I'm not sure"), ('no', 'No')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('place_of_worship', 'Place of worship'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('vote', 'Ability to vote was impacted'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('discriminated_against', 'Otherwise discriminated against'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('denied_housing', 'Denied housing or subjected to harmful living conditions')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('not_sure', "I'm not sure"), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('private_facility', 'Private facility'), ('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('private_facility', 'Private facility'), ('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='report',
            name='respondent_state',
        ),
        migrations.AddField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('NJ', 'New Jersey '), ('OK', 'Oklahoma '), ('SC', 'South Carolina '), ('ND', 'North Dakota '), ('CA', 'California '), ('NC', 'North Carolina '), ('DC', 'District of Columbia '), ('VA', 'Virginia '), ('VI', 'Virgin Islands '), ('CT', 'Connecticut '), ('IN', 'Indiana '), ('KS', 'Kansas '), ('GA', 'Georgia '), ('CO', 'Colorado '), ('AZ', 'Arizona '), ('TX', 'Texas '), ('NV', 'Nevada '), ('LA', 'Louisiana '), ('DE', 'Delaware '), ('NE', 'Nebraska '), ('AK', 'Alaska '), ('IL', 'Illinois '), ('AE', 'Armed Forces Africa '), ('PA', 'Pennsylvania '), ('AA', 'Armed Forces Americas '), ('HI', 'Hawaii '), ('WI', 'Wisconsin '), ('TN', 'Tennessee '), ('WY', 'Wyoming '), ('SD', 'South Dakota '), ('PR', 'Puerto Rico '), ('AE', 'Armed Forces Europe '), ('MD', 'Maryland '), ('NH', 'New Hampshire '), ('VT', 'Vermont '), ('ME', 'Maine '), ('NM', 'New Mexico '), ('OH', 'Ohio '), ('UT', 'Utah '), ('AL', 'Alabama '), ('NY', 'New York '), ('KY', 'Kentucky '), ('AR', 'Arkansas '), ('MI', 'Michigan '), ('AE', 'Armed Forces Canada '), ('MO', 'Missouri '), ('MS', 'Mississippi '), ('WV', 'West Virginia '), ('ID', 'Idaho '), ('IA', 'Iowa '), ('MN', 'Minnesota '), ('RI', 'Rhode Island '), ('GU', 'Guam '), ('AS', 'American Samoa '), ('FL', 'Florida '), ('MT', 'Montana '), ('MP', 'Northern Mariana Islands '), ('MA', 'Massachusetts '), ('AP', 'Armed Forces Pacific '), ('WA', 'Washington '), ('AE', 'Armed Forces Middle East '), ('OR', 'Oregon ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('lender', 'Bank or loaning service'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('healthcare', 'Healthcare provider or staff'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('other_public_official', 'Other public official (judge, voting official, or other government official)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('last_6_months', 'Within the last 6 months'), ('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('lender', 'Bank or loaning service'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('healthcare', 'Healthcare provider or staff'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('other_public_official', 'Other public official (judge, voting official, or other government official)')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StatesAndTerritories',
        ),
    ]
