# Generated by Django 2.2.3 on 2019-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0012_auto_20190815_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('MT', 'Montana '), ('VA', 'Virginia '), ('VT', 'Vermont '), ('OK', 'Oklahoma '), ('MP', 'Northern Mariana Islands '), ('KY', 'Kentucky '), ('IA', 'Iowa '), ('MO', 'Missouri '), ('MI', 'Michigan '), ('IL', 'Illinois '), ('HI', 'Hawaii '), ('KS', 'Kansas '), ('MA', 'Massachusetts '), ('UT', 'Utah '), ('AP', 'Armed Forces Pacific '), ('ID', 'Idaho '), ('WA', 'Washington '), ('AE', 'Armed Forces Europe '), ('NY', 'New York '), ('NV', 'Nevada '), ('GA', 'Georgia '), ('MN', 'Minnesota '), ('DE', 'Delaware '), ('MS', 'Mississippi '), ('NJ', 'New Jersey '), ('TN', 'Tennessee '), ('CA', 'California '), ('AK', 'Alaska '), ('DC', 'District of Columbia '), ('SC', 'South Carolina '), ('AE', 'Armed Forces Africa '), ('AR', 'Arkansas '), ('WI', 'Wisconsin '), ('CO', 'Colorado '), ('RI', 'Rhode Island '), ('AS', 'American Samoa '), ('MD', 'Maryland '), ('OR', 'Oregon '), ('FL', 'Florida '), ('ND', 'North Dakota '), ('WV', 'West Virginia '), ('IN', 'Indiana '), ('WY', 'Wyoming '), ('AZ', 'Arizona '), ('ME', 'Maine '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('VI', 'Virgin Islands '), ('TX', 'Texas '), ('NH', 'New Hampshire '), ('PA', 'Pennsylvania '), ('AE', 'Armed Forces Middle East '), ('AL', 'Alabama '), ('SD', 'South Dakota '), ('CT', 'Connecticut '), ('OH', 'Ohio '), ('NM', 'New Mexico '), ('NC', 'North Carolina '), ('PR', 'Puerto Rico '), ('LA', 'Louisiana '), ('GU', 'Guam '), ('NE', 'Nebraska ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(blank=True, choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('not_sure', "I'm not sure")], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('workplace', 'Workplace or potential workplace'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('place_of_worship', 'Place of worship'), ('government_building', 'Another government building (courthouse, DMV, post office)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('discriminated_against', 'Otherwise discriminated against'), ('vote', 'Ability to vote was impacted'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('denied_housing', 'Denied housing or subjected to harmful living conditions')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('not_sure', "I'm not sure")], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(blank=True, choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(blank=True, choices=[('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('not_sure', "I'm not sure")], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('MT', 'Montana '), ('VA', 'Virginia '), ('VT', 'Vermont '), ('OK', 'Oklahoma '), ('MP', 'Northern Mariana Islands '), ('KY', 'Kentucky '), ('IA', 'Iowa '), ('MO', 'Missouri '), ('MI', 'Michigan '), ('IL', 'Illinois '), ('HI', 'Hawaii '), ('KS', 'Kansas '), ('MA', 'Massachusetts '), ('UT', 'Utah '), ('AP', 'Armed Forces Pacific '), ('ID', 'Idaho '), ('WA', 'Washington '), ('AE', 'Armed Forces Europe '), ('NY', 'New York '), ('NV', 'Nevada '), ('GA', 'Georgia '), ('MN', 'Minnesota '), ('DE', 'Delaware '), ('MS', 'Mississippi '), ('NJ', 'New Jersey '), ('TN', 'Tennessee '), ('CA', 'California '), ('AK', 'Alaska '), ('DC', 'District of Columbia '), ('SC', 'South Carolina '), ('AE', 'Armed Forces Africa '), ('AR', 'Arkansas '), ('WI', 'Wisconsin '), ('CO', 'Colorado '), ('RI', 'Rhode Island '), ('AS', 'American Samoa '), ('MD', 'Maryland '), ('OR', 'Oregon '), ('FL', 'Florida '), ('ND', 'North Dakota '), ('WV', 'West Virginia '), ('IN', 'Indiana '), ('WY', 'Wyoming '), ('AZ', 'Arizona '), ('ME', 'Maine '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('VI', 'Virgin Islands '), ('TX', 'Texas '), ('NH', 'New Hampshire '), ('PA', 'Pennsylvania '), ('AE', 'Armed Forces Middle East '), ('AL', 'Alabama '), ('SD', 'South Dakota '), ('CT', 'Connecticut '), ('OH', 'Ohio '), ('NM', 'New Mexico '), ('NC', 'North Carolina '), ('PR', 'Puerto Rico '), ('LA', 'Louisiana '), ('GU', 'Guam '), ('NE', 'Nebraska ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(blank=True, choices=[('last_3_years', 'Within the last 3 years'), ('greater_than_3_years', 'More than 3 years ago'), ('last_6_months', 'Within the last 6 months')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], max_length=100, null=True),
        ),
    ]
