# Generated by Django 2.2.4 on 2019-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0013_rename_protected_class'),

    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('workplace', 'Workplace discrimination or other employment-related problem.'), ('housing', 'Housing discrimination or harassment.'), ('education', 'Discrimination at a school, educational program, or related to receiving education.'), ('voting', 'Right to vote impacted.'), ('police', 'Mistreated by police, law enforcement, or correctional staff (including while in prison).'), ('commercial_or_public', 'Discriminated against in any other commercial location or public place.'), ('something_else', 'Something else happened.')], default='', max_length=100),
        ),
    ]
