# Generated by Django 2.2.3 on 2019-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0013_auto_20190816_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('HI', 'Hawaii '), ('AE', 'Armed Forces Africa '), ('ID', 'Idaho '), ('UT', 'Utah '), ('SD', 'South Dakota '), ('IL', 'Illinois '), ('NE', 'Nebraska '), ('IN', 'Indiana '), ('ND', 'North Dakota '), ('NH', 'New Hampshire '), ('AS', 'American Samoa '), ('AR', 'Arkansas '), ('TX', 'Texas '), ('GA', 'Georgia '), ('FL', 'Florida '), ('OR', 'Oregon '), ('GU', 'Guam '), ('AE', 'Armed Forces Canada '), ('SC', 'South Carolina '), ('AE', 'Armed Forces Middle East '), ('WV', 'West Virginia '), ('PR', 'Puerto Rico '), ('MN', 'Minnesota '), ('NY', 'New York '), ('CA', 'California '), ('DE', 'Delaware '), ('CT', 'Connecticut '), ('MD', 'Maryland '), ('MI', 'Michigan '), ('WY', 'Wyoming '), ('MA', 'Massachusetts '), ('WI', 'Wisconsin '), ('MP', 'Northern Mariana Islands '), ('DC', 'District of Columbia '), ('RI', 'Rhode Island '), ('TN', 'Tennessee '), ('AZ', 'Arizona '), ('NC', 'North Carolina '), ('OK', 'Oklahoma '), ('KY', 'Kentucky '), ('MO', 'Missouri '), ('VT', 'Vermont '), ('AE', 'Armed Forces Europe '), ('LA', 'Louisiana '), ('WA', 'Washington '), ('PA', 'Pennsylvania '), ('MT', 'Montana '), ('AA', 'Armed Forces Americas '), ('NJ', 'New Jersey '), ('AK', 'Alaska '), ('NM', 'New Mexico '), ('IA', 'Iowa '), ('NV', 'Nevada '), ('CO', 'Colorado '), ('KS', 'Kansas '), ('OH', 'Ohio '), ('ME', 'Maine '), ('MS', 'Mississippi '), ('VA', 'Virginia '), ('AP', 'Armed Forces Pacific '), ('VI', 'Virgin Islands '), ('AL', 'Alabama ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(choices=[('15_or_more', '15 or more employees'), ('14_or_less', 'Fewer than 15 employees')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('not_sure', "I'm not sure"), ('no', 'No'), ('yes', 'Yes')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('workplace', 'Workplace or potential workplace'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('place_of_worship', 'Place of worship')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('discriminated_against', 'Otherwise discriminated against'), ('vote', 'Ability to vote was impacted'), ('denied_access', 'Denied access or removed from a location (including segregation)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure"), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('undisclosed', 'I prefer not to disclose'), ('another', "I'm reporting on behalf of another person"), ('myself', "I'm reporting for myself")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('HI', 'Hawaii '), ('AE', 'Armed Forces Africa '), ('ID', 'Idaho '), ('UT', 'Utah '), ('SD', 'South Dakota '), ('IL', 'Illinois '), ('NE', 'Nebraska '), ('IN', 'Indiana '), ('ND', 'North Dakota '), ('NH', 'New Hampshire '), ('AS', 'American Samoa '), ('AR', 'Arkansas '), ('TX', 'Texas '), ('GA', 'Georgia '), ('FL', 'Florida '), ('OR', 'Oregon '), ('GU', 'Guam '), ('AE', 'Armed Forces Canada '), ('SC', 'South Carolina '), ('AE', 'Armed Forces Middle East '), ('WV', 'West Virginia '), ('PR', 'Puerto Rico '), ('MN', 'Minnesota '), ('NY', 'New York '), ('CA', 'California '), ('DE', 'Delaware '), ('CT', 'Connecticut '), ('MD', 'Maryland '), ('MI', 'Michigan '), ('WY', 'Wyoming '), ('MA', 'Massachusetts '), ('WI', 'Wisconsin '), ('MP', 'Northern Mariana Islands '), ('DC', 'District of Columbia '), ('RI', 'Rhode Island '), ('TN', 'Tennessee '), ('AZ', 'Arizona '), ('NC', 'North Carolina '), ('OK', 'Oklahoma '), ('KY', 'Kentucky '), ('MO', 'Missouri '), ('VT', 'Vermont '), ('AE', 'Armed Forces Europe '), ('LA', 'Louisiana '), ('WA', 'Washington '), ('PA', 'Pennsylvania '), ('MT', 'Montana '), ('AA', 'Armed Forces Americas '), ('NJ', 'New Jersey '), ('AK', 'Alaska '), ('NM', 'New Mexico '), ('IA', 'Iowa '), ('NV', 'Nevada '), ('CO', 'Colorado '), ('KS', 'Kansas '), ('OH', 'Ohio '), ('ME', 'Maine '), ('MS', 'Mississippi '), ('VA', 'Virginia '), ('AP', 'Armed Forces Pacific '), ('VI', 'Virgin Islands '), ('AL', 'Alabama ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('healthcare', 'Healthcare provider or staff'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('employer', 'Employer or potential employer'), ('lender', 'Bank or loaning service'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(blank=True, choices=[('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('employer', 'Employer or potential employer'), ('lender', 'Bank or loaning service'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('healthcare', 'Healthcare provider or staff')], max_length=100, null=True),
        ),
    ]
