# Generated by Django 2.2.4 on 2019-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0014_auto_20190816_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('AP', 'Armed Forces Pacific '), ('FL', 'Florida '), ('HI', 'Hawaii '), ('CT', 'Connecticut '), ('LA', 'Louisiana '), ('VA', 'Virginia '), ('IL', 'Illinois '), ('ME', 'Maine '), ('WV', 'West Virginia '), ('TN', 'Tennessee '), ('GU', 'Guam '), ('MA', 'Massachusetts '), ('NE', 'Nebraska '), ('IN', 'Indiana '), ('WY', 'Wyoming '), ('MN', 'Minnesota '), ('MT', 'Montana '), ('AE', 'Armed Forces Canada '), ('AK', 'Alaska '), ('DC', 'District of Columbia '), ('MD', 'Maryland '), ('NH', 'New Hampshire '), ('IA', 'Iowa '), ('VT', 'Vermont '), ('WA', 'Washington '), ('AS', 'American Samoa '), ('AL', 'Alabama '), ('OR', 'Oregon '), ('KY', 'Kentucky '), ('NM', 'New Mexico '), ('AA', 'Armed Forces Americas '), ('AZ', 'Arizona '), ('MP', 'Northern Mariana Islands '), ('VI', 'Virgin Islands '), ('TX', 'Texas '), ('ID', 'Idaho '), ('AR', 'Arkansas '), ('KS', 'Kansas '), ('RI', 'Rhode Island '), ('PR', 'Puerto Rico '), ('NY', 'New York '), ('DE', 'Delaware '), ('MO', 'Missouri '), ('GA', 'Georgia '), ('MI', 'Michigan '), ('UT', 'Utah '), ('AE', 'Armed Forces Middle East '), ('NV', 'Nevada '), ('OK', 'Oklahoma '), ('ND', 'North Dakota '), ('WI', 'Wisconsin '), ('SC', 'South Carolina '), ('PA', 'Pennsylvania '), ('NJ', 'New Jersey '), ('AE', 'Armed Forces Europe '), ('NC', 'North Carolina '), ('CA', 'California '), ('SD', 'South Dakota '), ('AE', 'Armed Forces Africa '), ('MS', 'Mississippi '), ('CO', 'Colorado '), ('OH', 'Ohio ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('not_sure', "I'm not sure")], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('place_of_worship', 'Place of worship')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_access', 'Denied access or removed from a location (including segregation)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('federal_facility', 'Federal facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('private_facility', 'Private facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('federal_facility', 'Federal facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('private_facility', 'Private facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('public', 'Public -- Schools or programs funded by local, state, or the federal government')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('AP', 'Armed Forces Pacific '), ('FL', 'Florida '), ('HI', 'Hawaii '), ('CT', 'Connecticut '), ('LA', 'Louisiana '), ('VA', 'Virginia '), ('IL', 'Illinois '), ('ME', 'Maine '), ('WV', 'West Virginia '), ('TN', 'Tennessee '), ('GU', 'Guam '), ('MA', 'Massachusetts '), ('NE', 'Nebraska '), ('IN', 'Indiana '), ('WY', 'Wyoming '), ('MN', 'Minnesota '), ('MT', 'Montana '), ('AE', 'Armed Forces Canada '), ('AK', 'Alaska '), ('DC', 'District of Columbia '), ('MD', 'Maryland '), ('NH', 'New Hampshire '), ('IA', 'Iowa '), ('VT', 'Vermont '), ('WA', 'Washington '), ('AS', 'American Samoa '), ('AL', 'Alabama '), ('OR', 'Oregon '), ('KY', 'Kentucky '), ('NM', 'New Mexico '), ('AA', 'Armed Forces Americas '), ('AZ', 'Arizona '), ('MP', 'Northern Mariana Islands '), ('VI', 'Virgin Islands '), ('TX', 'Texas '), ('ID', 'Idaho '), ('AR', 'Arkansas '), ('KS', 'Kansas '), ('RI', 'Rhode Island '), ('PR', 'Puerto Rico '), ('NY', 'New York '), ('DE', 'Delaware '), ('MO', 'Missouri '), ('GA', 'Georgia '), ('MI', 'Michigan '), ('UT', 'Utah '), ('AE', 'Armed Forces Middle East '), ('NV', 'Nevada '), ('OK', 'Oklahoma '), ('ND', 'North Dakota '), ('WI', 'Wisconsin '), ('SC', 'South Carolina '), ('PA', 'Pennsylvania '), ('NJ', 'New Jersey '), ('AE', 'Armed Forces Europe '), ('NC', 'North Carolina '), ('CA', 'California '), ('SD', 'South Dakota '), ('AE', 'Armed Forces Africa '), ('MS', 'Mississippi '), ('CO', 'Colorado '), ('OH', 'Ohio ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('employer', 'Employer or potential employer')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('last_6_months', 'Within the last 6 months'), ('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('employer', 'Employer or potential employer')], default='employer', max_length=100),
            preserve_default=False,
        ),
    ]
