# Generated by Django 2.2.4 on 2019-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0015_auto_20191113_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_section',
            field=models.TextField(choices=[('ADM', 'Administrative'), ('IER', 'Immigrant and Employee Rights'), ('VOT', 'Voting'), ('DRS', 'Disability'), ('CRM', 'Criminal'), ('HCE', 'Housing'), ('EOS', 'Education'), ('SPL', 'Special Litigation'), ('ELS', 'Employment Litigation Services'), ('FCS', 'Federal Coordination and Compliance')], default='ADM'),
        ),
    ]
