# Generated by Django 2.2.4 on 2019-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0016_auto_20190821_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('SD', 'South Dakota '), ('KY', 'Kentucky '), ('AL', 'Alabama '), ('PR', 'Puerto Rico '), ('IL', 'Illinois '), ('ID', 'Idaho '), ('OR', 'Oregon '), ('SC', 'South Carolina '), ('NM', 'New Mexico '), ('TN', 'Tennessee '), ('NC', 'North Carolina '), ('VI', 'Virgin Islands '), ('UT', 'Utah '), ('MI', 'Michigan '), ('CO', 'Colorado '), ('MO', 'Missouri '), ('ND', 'North Dakota '), ('AE', 'Armed Forces Canada '), ('KS', 'Kansas '), ('AZ', 'Arizona '), ('AP', 'Armed Forces Pacific '), ('MS', 'Mississippi '), ('RI', 'Rhode Island '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('IN', 'Indiana '), ('OH', 'Ohio '), ('VA', 'Virginia '), ('AS', 'American Samoa '), ('DC', 'District of Columbia '), ('FL', 'Florida '), ('AK', 'Alaska '), ('GA', 'Georgia '), ('CA', 'California '), ('LA', 'Louisiana '), ('MT', 'Montana '), ('NH', 'New Hampshire '), ('TX', 'Texas '), ('VT', 'Vermont '), ('NY', 'New York '), ('WA', 'Washington '), ('WV', 'West Virginia '), ('AR', 'Arkansas '), ('ME', 'Maine '), ('CT', 'Connecticut '), ('WY', 'Wyoming '), ('MN', 'Minnesota '), ('AA', 'Armed Forces Americas '), ('NE', 'Nebraska '), ('NV', 'Nevada '), ('MD', 'Maryland '), ('WI', 'Wisconsin '), ('MP', 'Northern Mariana Islands '), ('DE', 'Delaware '), ('OK', 'Oklahoma '), ('AE', 'Armed Forces Africa '), ('NJ', 'New Jersey '), ('MA', 'Massachusetts '), ('PA', 'Pennsylvania '), ('GU', 'Guam '), ('HI', 'Hawaii '), ('IA', 'Iowa ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('not_sure', "I'm not sure")], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('place_of_worship', 'Place of worship'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('workplace', 'Workplace or potential workplace')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('vote', 'Ability to vote was impacted'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('discriminated_against', 'Otherwise discriminated against'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('myself', "I'm reporting for myself"), ('undisclosed', 'I prefer not to disclose'), ('another', "I'm reporting on behalf of another person")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('SD', 'South Dakota '), ('KY', 'Kentucky '), ('AL', 'Alabama '), ('PR', 'Puerto Rico '), ('IL', 'Illinois '), ('ID', 'Idaho '), ('OR', 'Oregon '), ('SC', 'South Carolina '), ('NM', 'New Mexico '), ('TN', 'Tennessee '), ('NC', 'North Carolina '), ('VI', 'Virgin Islands '), ('UT', 'Utah '), ('MI', 'Michigan '), ('CO', 'Colorado '), ('MO', 'Missouri '), ('ND', 'North Dakota '), ('AE', 'Armed Forces Canada '), ('KS', 'Kansas '), ('AZ', 'Arizona '), ('AP', 'Armed Forces Pacific '), ('MS', 'Mississippi '), ('RI', 'Rhode Island '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('IN', 'Indiana '), ('OH', 'Ohio '), ('VA', 'Virginia '), ('AS', 'American Samoa '), ('DC', 'District of Columbia '), ('FL', 'Florida '), ('AK', 'Alaska '), ('GA', 'Georgia '), ('CA', 'California '), ('LA', 'Louisiana '), ('MT', 'Montana '), ('NH', 'New Hampshire '), ('TX', 'Texas '), ('VT', 'Vermont '), ('NY', 'New York '), ('WA', 'Washington '), ('WV', 'West Virginia '), ('AR', 'Arkansas '), ('ME', 'Maine '), ('CT', 'Connecticut '), ('WY', 'Wyoming '), ('MN', 'Minnesota '), ('AA', 'Armed Forces Americas '), ('NE', 'Nebraska '), ('NV', 'Nevada '), ('MD', 'Maryland '), ('WI', 'Wisconsin '), ('MP', 'Northern Mariana Islands '), ('DE', 'Delaware '), ('OK', 'Oklahoma '), ('AE', 'Armed Forces Africa '), ('NJ', 'New Jersey '), ('MA', 'Massachusetts '), ('PA', 'Pennsylvania '), ('GU', 'Guam '), ('HI', 'Hawaii '), ('IA', 'Iowa ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('healthcare', 'Healthcare provider or staff'), ('lender', 'Bank or loaning service'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('last_6_months', 'Within the last 6 months'), ('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('healthcare', 'Healthcare provider or staff'), ('lender', 'Bank or loaning service'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], max_length=100),
        ),
    ]
