# Generated by Django 2.2.4 on 2019-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0017_auto_20191118_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='violation_summary',
            field=models.TextField(default='previous record', max_length=7000),
        ),
    ]
