# Generated by Django 2.2.4 on 2019-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0017_auto_20190821_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('AA', 'Armed Forces Americas '), ('IL', 'Illinois '), ('SD', 'South Dakota '), ('ID', 'Idaho '), ('NC', 'North Carolina '), ('GU', 'Guam '), ('VI', 'Virgin Islands '), ('ND', 'North Dakota '), ('AE', 'Armed Forces Middle East '), ('KY', 'Kentucky '), ('AZ', 'Arizona '), ('NM', 'New Mexico '), ('UT', 'Utah '), ('VT', 'Vermont '), ('GA', 'Georgia '), ('CO', 'Colorado '), ('RI', 'Rhode Island '), ('IN', 'Indiana '), ('MA', 'Massachusetts '), ('MT', 'Montana '), ('AL', 'Alabama '), ('NE', 'Nebraska '), ('MO', 'Missouri '), ('AS', 'American Samoa '), ('SC', 'South Carolina '), ('PR', 'Puerto Rico '), ('AP', 'Armed Forces Pacific '), ('AE', 'Armed Forces Europe '), ('NH', 'New Hampshire '), ('MN', 'Minnesota '), ('PA', 'Pennsylvania '), ('ME', 'Maine '), ('WY', 'Wyoming '), ('TX', 'Texas '), ('OK', 'Oklahoma '), ('CA', 'California '), ('WI', 'Wisconsin '), ('MP', 'Northern Mariana Islands '), ('MI', 'Michigan '), ('HI', 'Hawaii '), ('DE', 'Delaware '), ('LA', 'Louisiana '), ('MS', 'Mississippi '), ('VA', 'Virginia '), ('TN', 'Tennessee '), ('OH', 'Ohio '), ('OR', 'Oregon '), ('KS', 'Kansas '), ('FL', 'Florida '), ('CT', 'Connecticut '), ('NY', 'New York '), ('MD', 'Maryland '), ('WV', 'West Virginia '), ('AK', 'Alaska '), ('AE', 'Armed Forces Africa '), ('DC', 'District of Columbia '), ('NV', 'Nevada '), ('NJ', 'New Jersey '), ('AR', 'Arkansas '), ('WA', 'Washington '), ('AE', 'Armed Forces Canada '), ('IA', 'Iowa ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('not_sure', "I'm not sure"), ('yes', 'Yes'), ('no', 'No')], default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('workplace', 'Workplace or potential workplace'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('place_of_worship', 'Place of worship')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure"), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose'), ('myself', "I'm reporting for myself")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('AA', 'Armed Forces Americas '), ('IL', 'Illinois '), ('SD', 'South Dakota '), ('ID', 'Idaho '), ('NC', 'North Carolina '), ('GU', 'Guam '), ('VI', 'Virgin Islands '), ('ND', 'North Dakota '), ('AE', 'Armed Forces Middle East '), ('KY', 'Kentucky '), ('AZ', 'Arizona '), ('NM', 'New Mexico '), ('UT', 'Utah '), ('VT', 'Vermont '), ('GA', 'Georgia '), ('CO', 'Colorado '), ('RI', 'Rhode Island '), ('IN', 'Indiana '), ('MA', 'Massachusetts '), ('MT', 'Montana '), ('AL', 'Alabama '), ('NE', 'Nebraska '), ('MO', 'Missouri '), ('AS', 'American Samoa '), ('SC', 'South Carolina '), ('PR', 'Puerto Rico '), ('AP', 'Armed Forces Pacific '), ('AE', 'Armed Forces Europe '), ('NH', 'New Hampshire '), ('MN', 'Minnesota '), ('PA', 'Pennsylvania '), ('ME', 'Maine '), ('WY', 'Wyoming '), ('TX', 'Texas '), ('OK', 'Oklahoma '), ('CA', 'California '), ('WI', 'Wisconsin '), ('MP', 'Northern Mariana Islands '), ('MI', 'Michigan '), ('HI', 'Hawaii '), ('DE', 'Delaware '), ('LA', 'Louisiana '), ('MS', 'Mississippi '), ('VA', 'Virginia '), ('TN', 'Tennessee '), ('OH', 'Ohio '), ('OR', 'Oregon '), ('KS', 'Kansas '), ('FL', 'Florida '), ('CT', 'Connecticut '), ('NY', 'New York '), ('MD', 'Maryland '), ('WV', 'West Virginia '), ('AK', 'Alaska '), ('AE', 'Armed Forces Africa '), ('DC', 'District of Columbia '), ('NV', 'Nevada '), ('NJ', 'New Jersey '), ('AR', 'Arkansas '), ('WA', 'Washington '), ('AE', 'Armed Forces Canada '), ('IA', 'Iowa ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('lender', 'Bank or loaning service'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years'), ('last_6_months', 'Within the last 6 months')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('lender', 'Bank or loaning service'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], max_length=100),
        ),
    ]
