# Generated by Django 2.2.4 on 2019-08-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0019_auto_20190821_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('DC', 'District of Columbia '), ('AE', 'Armed Forces Africa '), ('AE', 'Armed Forces Canada '), ('OR', 'Oregon '), ('AR', 'Arkansas '), ('FL', 'Florida '), ('AK', 'Alaska '), ('NV', 'Nevada '), ('NH', 'New Hampshire '), ('NC', 'North Carolina '), ('MP', 'Northern Mariana Islands '), ('RI', 'Rhode Island '), ('KY', 'Kentucky '), ('WY', 'Wyoming '), ('MO', 'Missouri '), ('CT', 'Connecticut '), ('MA', 'Massachusetts '), ('NY', 'New York '), ('WA', 'Washington '), ('UT', 'Utah '), ('DE', 'Delaware '), ('WV', 'West Virginia '), ('AL', 'Alabama '), ('VA', 'Virginia '), ('VT', 'Vermont '), ('NE', 'Nebraska '), ('GU', 'Guam '), ('ND', 'North Dakota '), ('AE', 'Armed Forces Middle East '), ('ID', 'Idaho '), ('WI', 'Wisconsin '), ('HI', 'Hawaii '), ('CO', 'Colorado '), ('MD', 'Maryland '), ('AP', 'Armed Forces Pacific '), ('MS', 'Mississippi '), ('AE', 'Armed Forces Europe '), ('IA', 'Iowa '), ('TN', 'Tennessee '), ('MN', 'Minnesota '), ('OH', 'Ohio '), ('TX', 'Texas '), ('AZ', 'Arizona '), ('SC', 'South Carolina '), ('GA', 'Georgia '), ('MI', 'Michigan '), ('AA', 'Armed Forces Americas '), ('LA', 'Louisiana '), ('CA', 'California '), ('IN', 'Indiana '), ('KS', 'Kansas '), ('PA', 'Pennsylvania '), ('NM', 'New Mexico '), ('MT', 'Montana '), ('OK', 'Oklahoma '), ('IL', 'Illinois '), ('NJ', 'New Jersey '), ('AS', 'American Samoa '), ('SD', 'South Dakota '), ('VI', 'Virgin Islands '), ('ME', 'Maine '), ('PR', 'Puerto Rico ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('yes', 'Yes'), ('not_sure', "I'm not sure"), ('no', 'No')], default='no', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('workplace', 'Workplace or potential workplace'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('place_of_worship', 'Place of worship'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('prevented_from_service', 'Prevented from using a service or service terminated')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure"), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('undisclosed', 'I prefer not to disclose'), ('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('DC', 'District of Columbia '), ('AE', 'Armed Forces Africa '), ('AE', 'Armed Forces Canada '), ('OR', 'Oregon '), ('AR', 'Arkansas '), ('FL', 'Florida '), ('AK', 'Alaska '), ('NV', 'Nevada '), ('NH', 'New Hampshire '), ('NC', 'North Carolina '), ('MP', 'Northern Mariana Islands '), ('RI', 'Rhode Island '), ('KY', 'Kentucky '), ('WY', 'Wyoming '), ('MO', 'Missouri '), ('CT', 'Connecticut '), ('MA', 'Massachusetts '), ('NY', 'New York '), ('WA', 'Washington '), ('UT', 'Utah '), ('DE', 'Delaware '), ('WV', 'West Virginia '), ('AL', 'Alabama '), ('VA', 'Virginia '), ('VT', 'Vermont '), ('NE', 'Nebraska '), ('GU', 'Guam '), ('ND', 'North Dakota '), ('AE', 'Armed Forces Middle East '), ('ID', 'Idaho '), ('WI', 'Wisconsin '), ('HI', 'Hawaii '), ('CO', 'Colorado '), ('MD', 'Maryland '), ('AP', 'Armed Forces Pacific '), ('MS', 'Mississippi '), ('AE', 'Armed Forces Europe '), ('IA', 'Iowa '), ('TN', 'Tennessee '), ('MN', 'Minnesota '), ('OH', 'Ohio '), ('TX', 'Texas '), ('AZ', 'Arizona '), ('SC', 'South Carolina '), ('GA', 'Georgia '), ('MI', 'Michigan '), ('AA', 'Armed Forces Americas '), ('LA', 'Louisiana '), ('CA', 'California '), ('IN', 'Indiana '), ('KS', 'Kansas '), ('PA', 'Pennsylvania '), ('NM', 'New Mexico '), ('MT', 'Montana '), ('OK', 'Oklahoma '), ('IL', 'Illinois '), ('NJ', 'New Jersey '), ('AS', 'American Samoa '), ('SD', 'South Dakota '), ('VI', 'Virgin Islands '), ('ME', 'Maine '), ('PR', 'Puerto Rico ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('last_3_years', 'Within the last 3 years'), ('last_6_months', 'Within the last 6 months'), ('greater_than_3_years', 'More than 3 years ago')], max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], max_length=100),
        ),
    ]
