# Generated by Django 2.2.4 on 2019-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0019_auto_20191122_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='contact_address_line_2',
            new_name='location_address_line_1',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='contact_address_line_1',
            new_name='location_address_line_2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='contact_state',
        ),
        migrations.RemoveField(
            model_name='report',
            name='place',
        ),
        migrations.AddField(
            model_name='report',
            name='location_city_town',
            field=models.CharField(default='previous record', max_length=700),
        ),
        migrations.AddField(
            model_name='report',
            name='location_name',
            field=models.CharField(default='previous record', max_length=225),
        ),
        migrations.AddField(
            model_name='report',
            name='location_state',
            field=models.CharField(choices=[('AL', 'Alabama '), ('AK', 'Alaska '), ('AZ', 'Arizona '), ('AR', 'Arkansas '), ('CA', 'California '), ('CO', 'Colorado '), ('CT', 'Connecticut '), ('DE', 'Delaware '), ('DC', 'District of Columbia '), ('FL', 'Florida '), ('GA', 'Georgia '), ('HI', 'Hawaii '), ('ID', 'Idaho '), ('IL', 'Illinois '), ('IN', 'Indiana '), ('IA', 'Iowa '), ('KS', 'Kansas '), ('KY', 'Kentucky '), ('LA', 'Louisiana '), ('ME', 'Maine '), ('MD', 'Maryland '), ('MA', 'Massachusetts '), ('MI', 'Michigan '), ('MN', 'Minnesota '), ('MS', 'Mississippi '), ('MO', 'Missouri '), ('MT', 'Montana '), ('NE', 'Nebraska '), ('NV', 'Nevada '), ('NH', 'New Hampshire '), ('NJ', 'New Jersey '), ('NM', 'New Mexico '), ('NY', 'New York '), ('NC', 'North Carolina '), ('ND', 'North Dakota '), ('OH', 'Ohio '), ('OK', 'Oklahoma '), ('OR', 'Oregon '), ('PA', 'Pennsylvania '), ('RI', 'Rhode Island '), ('SC', 'South Carolina '), ('SD', 'South Dakota '), ('TN', 'Tennessee '), ('TX', 'Texas '), ('UT', 'Utah '), ('VT', 'Vermont '), ('VA', 'Virginia '), ('WA', 'Washington '), ('WV', 'West Virginia '), ('WI', 'Wisconsin '), ('WY', 'Wyoming '), ('AS', 'American Samoa '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('PR', 'Puerto Rico '), ('VI', 'Virgin Islands '), ('AE', 'Armed Forces Africa '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('AP', 'Armed Forces Pacific ')], default='AL', max_length=100),
        ),
    ]
