# Generated by Django 2.2.4 on 2019-08-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0020_auto_20190821_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('CO', 'Colorado '), ('DC', 'District of Columbia '), ('MT', 'Montana '), ('TX', 'Texas '), ('VT', 'Vermont '), ('AE', 'Armed Forces Middle East '), ('ID', 'Idaho '), ('NV', 'Nevada '), ('MD', 'Maryland '), ('SD', 'South Dakota '), ('OK', 'Oklahoma '), ('SC', 'South Carolina '), ('IN', 'Indiana '), ('HI', 'Hawaii '), ('NY', 'New York '), ('CT', 'Connecticut '), ('MN', 'Minnesota '), ('WA', 'Washington '), ('AR', 'Arkansas '), ('WY', 'Wyoming '), ('AE', 'Armed Forces Europe '), ('NE', 'Nebraska '), ('MP', 'Northern Mariana Islands '), ('UT', 'Utah '), ('AE', 'Armed Forces Canada '), ('NJ', 'New Jersey '), ('PA', 'Pennsylvania '), ('OR', 'Oregon '), ('WV', 'West Virginia '), ('MI', 'Michigan '), ('GU', 'Guam '), ('DE', 'Delaware '), ('TN', 'Tennessee '), ('AL', 'Alabama '), ('MO', 'Missouri '), ('IA', 'Iowa '), ('VA', 'Virginia '), ('IL', 'Illinois '), ('CA', 'California '), ('MS', 'Mississippi '), ('AE', 'Armed Forces Africa '), ('VI', 'Virgin Islands '), ('ME', 'Maine '), ('NC', 'North Carolina '), ('AA', 'Armed Forces Americas '), ('PR', 'Puerto Rico '), ('NH', 'New Hampshire '), ('KY', 'Kentucky '), ('OH', 'Ohio '), ('FL', 'Florida '), ('AK', 'Alaska '), ('MA', 'Massachusetts '), ('LA', 'Louisiana '), ('GA', 'Georgia '), ('ND', 'North Dakota '), ('RI', 'Rhode Island '), ('KS', 'Kansas '), ('WI', 'Wisconsin '), ('AS', 'American Samoa '), ('AP', 'Armed Forces Pacific '), ('NM', 'New Mexico '), ('AZ', 'Arizona ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('not_sure', "I'm not sure")], max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('place_of_worship', 'Place of worship'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('workplace', 'Workplace or potential workplace'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('voting', 'Voting location or ballot (including mail-in ballots)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('vote', 'Ability to vote was impacted'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('discriminated_against', 'Otherwise discriminated against'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('CO', 'Colorado '), ('DC', 'District of Columbia '), ('MT', 'Montana '), ('TX', 'Texas '), ('VT', 'Vermont '), ('AE', 'Armed Forces Middle East '), ('ID', 'Idaho '), ('NV', 'Nevada '), ('MD', 'Maryland '), ('SD', 'South Dakota '), ('OK', 'Oklahoma '), ('SC', 'South Carolina '), ('IN', 'Indiana '), ('HI', 'Hawaii '), ('NY', 'New York '), ('CT', 'Connecticut '), ('MN', 'Minnesota '), ('WA', 'Washington '), ('AR', 'Arkansas '), ('WY', 'Wyoming '), ('AE', 'Armed Forces Europe '), ('NE', 'Nebraska '), ('MP', 'Northern Mariana Islands '), ('UT', 'Utah '), ('AE', 'Armed Forces Canada '), ('NJ', 'New Jersey '), ('PA', 'Pennsylvania '), ('OR', 'Oregon '), ('WV', 'West Virginia '), ('MI', 'Michigan '), ('GU', 'Guam '), ('DE', 'Delaware '), ('TN', 'Tennessee '), ('AL', 'Alabama '), ('MO', 'Missouri '), ('IA', 'Iowa '), ('VA', 'Virginia '), ('IL', 'Illinois '), ('CA', 'California '), ('MS', 'Mississippi '), ('AE', 'Armed Forces Africa '), ('VI', 'Virgin Islands '), ('ME', 'Maine '), ('NC', 'North Carolina '), ('AA', 'Armed Forces Americas '), ('PR', 'Puerto Rico '), ('NH', 'New Hampshire '), ('KY', 'Kentucky '), ('OH', 'Ohio '), ('FL', 'Florida '), ('AK', 'Alaska '), ('MA', 'Massachusetts '), ('LA', 'Louisiana '), ('GA', 'Georgia '), ('ND', 'North Dakota '), ('RI', 'Rhode Island '), ('KS', 'Kansas '), ('WI', 'Wisconsin '), ('AS', 'American Samoa '), ('AP', 'Armed Forces Pacific '), ('NM', 'New Mexico '), ('AZ', 'Arizona ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('healthcare', 'Healthcare provider or staff'), ('lender', 'Bank or loaning service'), ('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years'), ('last_6_months', 'Within the last 6 months')], max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('healthcare', 'Healthcare provider or staff'), ('employer', 'Employer or potential employer'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('lender', 'Bank or loaning service')], max_length=100),
        ),
    ]
