# Generated by Django 2.2.4 on 2019-08-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0021_auto_20190821_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('AE', 'Armed Forces Middle East '), ('SC', 'South Carolina '), ('AR', 'Arkansas '), ('ID', 'Idaho '), ('MN', 'Minnesota '), ('OR', 'Oregon '), ('PA', 'Pennsylvania '), ('DC', 'District of Columbia '), ('GA', 'Georgia '), ('HI', 'Hawaii '), ('MD', 'Maryland '), ('AP', 'Armed Forces Pacific '), ('NC', 'North Carolina '), ('KY', 'Kentucky '), ('NM', 'New Mexico '), ('NV', 'Nevada '), ('AK', 'Alaska '), ('NH', 'New Hampshire '), ('AL', 'Alabama '), ('WV', 'West Virginia '), ('IL', 'Illinois '), ('NY', 'New York '), ('CA', 'California '), ('AA', 'Armed Forces Americas '), ('TN', 'Tennessee '), ('VT', 'Vermont '), ('AZ', 'Arizona '), ('TX', 'Texas '), ('SD', 'South Dakota '), ('UT', 'Utah '), ('OH', 'Ohio '), ('MP', 'Northern Mariana Islands '), ('WA', 'Washington '), ('AE', 'Armed Forces Canada '), ('WI', 'Wisconsin '), ('CO', 'Colorado '), ('FL', 'Florida '), ('VI', 'Virgin Islands '), ('MS', 'Mississippi '), ('VA', 'Virginia '), ('DE', 'Delaware '), ('IN', 'Indiana '), ('KS', 'Kansas '), ('AE', 'Armed Forces Africa '), ('MI', 'Michigan '), ('RI', 'Rhode Island '), ('LA', 'Louisiana '), ('WY', 'Wyoming '), ('MO', 'Missouri '), ('OK', 'Oklahoma '), ('IA', 'Iowa '), ('NJ', 'New Jersey '), ('CT', 'Connecticut '), ('ME', 'Maine '), ('ND', 'North Dakota '), ('MT', 'Montana '), ('PR', 'Puerto Rico '), ('MA', 'Massachusetts '), ('AE', 'Armed Forces Europe '), ('AS', 'American Samoa '), ('GU', 'Guam '), ('NE', 'Nebraska ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', "I'm not sure")], max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('place_of_worship', 'Place of worship'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('vote', 'Ability to vote was impacted'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('discriminated_against', 'Otherwise discriminated against'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure"), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('state_local_facility', 'State or local facility'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('state_local_facility', 'State or local facility'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('not_sure', "I'm not sure"), ('public', 'Public -- Schools or programs funded by local, state, or the federal government')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('another', "I'm reporting on behalf of another person"), ('myself', "I'm reporting for myself"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('AE', 'Armed Forces Middle East '), ('SC', 'South Carolina '), ('AR', 'Arkansas '), ('ID', 'Idaho '), ('MN', 'Minnesota '), ('OR', 'Oregon '), ('PA', 'Pennsylvania '), ('DC', 'District of Columbia '), ('GA', 'Georgia '), ('HI', 'Hawaii '), ('MD', 'Maryland '), ('AP', 'Armed Forces Pacific '), ('NC', 'North Carolina '), ('KY', 'Kentucky '), ('NM', 'New Mexico '), ('NV', 'Nevada '), ('AK', 'Alaska '), ('NH', 'New Hampshire '), ('AL', 'Alabama '), ('WV', 'West Virginia '), ('IL', 'Illinois '), ('NY', 'New York '), ('CA', 'California '), ('AA', 'Armed Forces Americas '), ('TN', 'Tennessee '), ('VT', 'Vermont '), ('AZ', 'Arizona '), ('TX', 'Texas '), ('SD', 'South Dakota '), ('UT', 'Utah '), ('OH', 'Ohio '), ('MP', 'Northern Mariana Islands '), ('WA', 'Washington '), ('AE', 'Armed Forces Canada '), ('WI', 'Wisconsin '), ('CO', 'Colorado '), ('FL', 'Florida '), ('VI', 'Virgin Islands '), ('MS', 'Mississippi '), ('VA', 'Virginia '), ('DE', 'Delaware '), ('IN', 'Indiana '), ('KS', 'Kansas '), ('AE', 'Armed Forces Africa '), ('MI', 'Michigan '), ('RI', 'Rhode Island '), ('LA', 'Louisiana '), ('WY', 'Wyoming '), ('MO', 'Missouri '), ('OK', 'Oklahoma '), ('IA', 'Iowa '), ('NJ', 'New Jersey '), ('CT', 'Connecticut '), ('ME', 'Maine '), ('ND', 'North Dakota '), ('MT', 'Montana '), ('PR', 'Puerto Rico '), ('MA', 'Massachusetts '), ('AE', 'Armed Forces Europe '), ('AS', 'American Samoa '), ('GU', 'Guam '), ('NE', 'Nebraska ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('employer', 'Employer or potential employer'), ('lender', 'Bank or loaning service'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('last_6_months', 'Within the last 6 months'), ('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years')], max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)')], max_length=100),
        ),
    ]
