# Generated by Django 2.2.4 on 2019-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0022_auto_20190821_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('NV', 'Nevada '), ('UT', 'Utah '), ('VT', 'Vermont '), ('KY', 'Kentucky '), ('NH', 'New Hampshire '), ('OK', 'Oklahoma '), ('MN', 'Minnesota '), ('AE', 'Armed Forces Europe '), ('MO', 'Missouri '), ('OR', 'Oregon '), ('WA', 'Washington '), ('SC', 'South Carolina '), ('MT', 'Montana '), ('AK', 'Alaska '), ('HI', 'Hawaii '), ('NC', 'North Carolina '), ('DC', 'District of Columbia '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Canada '), ('AE', 'Armed Forces Middle East '), ('MP', 'Northern Mariana Islands '), ('AA', 'Armed Forces Americas '), ('CT', 'Connecticut '), ('CA', 'California '), ('NM', 'New Mexico '), ('PR', 'Puerto Rico '), ('MS', 'Mississippi '), ('AR', 'Arkansas '), ('FL', 'Florida '), ('MD', 'Maryland '), ('ND', 'North Dakota '), ('MA', 'Massachusetts '), ('WY', 'Wyoming '), ('VA', 'Virginia '), ('GU', 'Guam '), ('WI', 'Wisconsin '), ('VI', 'Virgin Islands '), ('ME', 'Maine '), ('AZ', 'Arizona '), ('GA', 'Georgia '), ('AP', 'Armed Forces Pacific '), ('PA', 'Pennsylvania '), ('IA', 'Iowa '), ('ID', 'Idaho '), ('NE', 'Nebraska '), ('IL', 'Illinois '), ('NY', 'New York '), ('IN', 'Indiana '), ('WV', 'West Virginia '), ('OH', 'Ohio '), ('AE', 'Armed Forces Africa '), ('NJ', 'New Jersey '), ('CO', 'Colorado '), ('AL', 'Alabama '), ('DE', 'Delaware '), ('RI', 'Rhode Island '), ('MI', 'Michigan '), ('KS', 'Kansas '), ('TX', 'Texas '), ('AS', 'American Samoa '), ('LA', 'Louisiana '), ('SD', 'South Dakota ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(choices=[('15_or_more', '15 or more employees'), ('14_or_less', 'Fewer than 15 employees')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('no', 'No'), ('not_sure', "I'm not sure"), ('yes', 'Yes')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('workplace', 'Workplace or potential workplace'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('place_of_worship', 'Place of worship'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('vote', 'Ability to vote was impacted'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('discriminated_against', 'Otherwise discriminated against')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('public', 'Public -- Schools or programs funded by local, state, or the federal government')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('undisclosed', 'I prefer not to disclose'), ('another', "I'm reporting on behalf of another person"), ('myself', "I'm reporting for myself")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('NV', 'Nevada '), ('UT', 'Utah '), ('VT', 'Vermont '), ('KY', 'Kentucky '), ('NH', 'New Hampshire '), ('OK', 'Oklahoma '), ('MN', 'Minnesota '), ('AE', 'Armed Forces Europe '), ('MO', 'Missouri '), ('OR', 'Oregon '), ('WA', 'Washington '), ('SC', 'South Carolina '), ('MT', 'Montana '), ('AK', 'Alaska '), ('HI', 'Hawaii '), ('NC', 'North Carolina '), ('DC', 'District of Columbia '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Canada '), ('AE', 'Armed Forces Middle East '), ('MP', 'Northern Mariana Islands '), ('AA', 'Armed Forces Americas '), ('CT', 'Connecticut '), ('CA', 'California '), ('NM', 'New Mexico '), ('PR', 'Puerto Rico '), ('MS', 'Mississippi '), ('AR', 'Arkansas '), ('FL', 'Florida '), ('MD', 'Maryland '), ('ND', 'North Dakota '), ('MA', 'Massachusetts '), ('WY', 'Wyoming '), ('VA', 'Virginia '), ('GU', 'Guam '), ('WI', 'Wisconsin '), ('VI', 'Virgin Islands '), ('ME', 'Maine '), ('AZ', 'Arizona '), ('GA', 'Georgia '), ('AP', 'Armed Forces Pacific '), ('PA', 'Pennsylvania '), ('IA', 'Iowa '), ('ID', 'Idaho '), ('NE', 'Nebraska '), ('IL', 'Illinois '), ('NY', 'New York '), ('IN', 'Indiana '), ('WV', 'West Virginia '), ('OH', 'Ohio '), ('AE', 'Armed Forces Africa '), ('NJ', 'New Jersey '), ('CO', 'Colorado '), ('AL', 'Alabama '), ('DE', 'Delaware '), ('RI', 'Rhode Island '), ('MI', 'Michigan '), ('KS', 'Kansas '), ('TX', 'Texas '), ('AS', 'American Samoa '), ('LA', 'Louisiana '), ('SD', 'South Dakota ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('healthcare', 'Healthcare provider or staff'), ('employer', 'Employer or potential employer'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('healthcare', 'Healthcare provider or staff'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('employer', 'Employer or potential employer'), ('lender', 'Bank or loaning service'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], max_length=100),
        ),
    ]
