# Generated by Django 2.2.4 on 2019-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0022_add_hate_crimes_and_trafficking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatecrimesandtrafficking',
            name='hatecrimes_trafficking_option',
            field=models.CharField(blank=True, choices=[('physical_harm', 'Physical harm or threats of violence based on race, color, national origin, religion, gender, sexual orientation, gender identity, or disability'), ('trafficking', 'Coerced or forced to do work or perform a commercial sex act')], max_length=500, null=True, unique=True),
        ),
    ]
