# Generated by Django 2.2.4 on 2019-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0023_auto_20190821_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('DE', 'Delaware '), ('PA', 'Pennsylvania '), ('NH', 'New Hampshire '), ('OH', 'Ohio '), ('AR', 'Arkansas '), ('CA', 'California '), ('UT', 'Utah '), ('FL', 'Florida '), ('OR', 'Oregon '), ('VI', 'Virgin Islands '), ('IN', 'Indiana '), ('WA', 'Washington '), ('PR', 'Puerto Rico '), ('AS', 'American Samoa '), ('AE', 'Armed Forces Africa '), ('MP', 'Northern Mariana Islands '), ('NE', 'Nebraska '), ('ND', 'North Dakota '), ('CT', 'Connecticut '), ('MS', 'Mississippi '), ('NY', 'New York '), ('LA', 'Louisiana '), ('NM', 'New Mexico '), ('HI', 'Hawaii '), ('ID', 'Idaho '), ('KS', 'Kansas '), ('IA', 'Iowa '), ('AZ', 'Arizona '), ('VT', 'Vermont '), ('WV', 'West Virginia '), ('AK', 'Alaska '), ('AP', 'Armed Forces Pacific '), ('NV', 'Nevada '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('WY', 'Wyoming '), ('AE', 'Armed Forces Canada '), ('MO', 'Missouri '), ('MD', 'Maryland '), ('GU', 'Guam '), ('TX', 'Texas '), ('WI', 'Wisconsin '), ('MA', 'Massachusetts '), ('SC', 'South Carolina '), ('ME', 'Maine '), ('CO', 'Colorado '), ('MI', 'Michigan '), ('RI', 'Rhode Island '), ('OK', 'Oklahoma '), ('AA', 'Armed Forces Americas '), ('MN', 'Minnesota '), ('NC', 'North Carolina '), ('AL', 'Alabama '), ('NJ', 'New Jersey '), ('GA', 'Georgia '), ('DC', 'District of Columbia '), ('IL', 'Illinois '), ('SD', 'South Dakota '), ('MT', 'Montana '), ('VA', 'Virginia '), ('KY', 'Kentucky ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('not_sure', "I'm not sure")], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('workplace', 'Workplace or potential workplace'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('place_of_worship', 'Place of worship')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('vote', 'Ability to vote was impacted'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('discriminated_against', 'Otherwise discriminated against'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_access', 'Denied access or removed from a location (including segregation)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('another', "I'm reporting on behalf of another person"), ('myself', "I'm reporting for myself"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('DE', 'Delaware '), ('PA', 'Pennsylvania '), ('NH', 'New Hampshire '), ('OH', 'Ohio '), ('AR', 'Arkansas '), ('CA', 'California '), ('UT', 'Utah '), ('FL', 'Florida '), ('OR', 'Oregon '), ('VI', 'Virgin Islands '), ('IN', 'Indiana '), ('WA', 'Washington '), ('PR', 'Puerto Rico '), ('AS', 'American Samoa '), ('AE', 'Armed Forces Africa '), ('MP', 'Northern Mariana Islands '), ('NE', 'Nebraska '), ('ND', 'North Dakota '), ('CT', 'Connecticut '), ('MS', 'Mississippi '), ('NY', 'New York '), ('LA', 'Louisiana '), ('NM', 'New Mexico '), ('HI', 'Hawaii '), ('ID', 'Idaho '), ('KS', 'Kansas '), ('IA', 'Iowa '), ('AZ', 'Arizona '), ('VT', 'Vermont '), ('WV', 'West Virginia '), ('AK', 'Alaska '), ('AP', 'Armed Forces Pacific '), ('NV', 'Nevada '), ('TN', 'Tennessee '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Middle East '), ('WY', 'Wyoming '), ('AE', 'Armed Forces Canada '), ('MO', 'Missouri '), ('MD', 'Maryland '), ('GU', 'Guam '), ('TX', 'Texas '), ('WI', 'Wisconsin '), ('MA', 'Massachusetts '), ('SC', 'South Carolina '), ('ME', 'Maine '), ('CO', 'Colorado '), ('MI', 'Michigan '), ('RI', 'Rhode Island '), ('OK', 'Oklahoma '), ('AA', 'Armed Forces Americas '), ('MN', 'Minnesota '), ('NC', 'North Carolina '), ('AL', 'Alabama '), ('NJ', 'New Jersey '), ('GA', 'Georgia '), ('DC', 'District of Columbia '), ('IL', 'Illinois '), ('SD', 'South Dakota '), ('MT', 'Montana '), ('VA', 'Virginia '), ('KY', 'Kentucky ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years'), ('greater_than_3_years', 'More than 3 years ago')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('employer', 'Employer or potential employer'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], max_length=100),
        ),
    ]
