# Generated by Django 2.2.4 on 2019-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0024_auto_20190821_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('NC', 'North Carolina '), ('OH', 'Ohio '), ('SC', 'South Carolina '), ('VI', 'Virgin Islands '), ('VA', 'Virginia '), ('AP', 'Armed Forces Pacific '), ('AZ', 'Arizona '), ('SD', 'South Dakota '), ('OK', 'Oklahoma '), ('NY', 'New York '), ('OR', 'Oregon '), ('KY', 'Kentucky '), ('TX', 'Texas '), ('MD', 'Maryland '), ('AE', 'Armed Forces Middle East '), ('ND', 'North Dakota '), ('IL', 'Illinois '), ('CO', 'Colorado '), ('NH', 'New Hampshire '), ('NV', 'Nevada '), ('CT', 'Connecticut '), ('ID', 'Idaho '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('GA', 'Georgia '), ('MT', 'Montana '), ('MO', 'Missouri '), ('LA', 'Louisiana '), ('DE', 'Delaware '), ('AS', 'American Samoa '), ('AK', 'Alaska '), ('IA', 'Iowa '), ('WY', 'Wyoming '), ('TN', 'Tennessee '), ('HI', 'Hawaii '), ('VT', 'Vermont '), ('CA', 'California '), ('KS', 'Kansas '), ('DC', 'District of Columbia '), ('AR', 'Arkansas '), ('NE', 'Nebraska '), ('NM', 'New Mexico '), ('MI', 'Michigan '), ('UT', 'Utah '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('MA', 'Massachusetts '), ('MS', 'Mississippi '), ('MN', 'Minnesota '), ('WI', 'Wisconsin '), ('IN', 'Indiana '), ('PA', 'Pennsylvania '), ('FL', 'Florida '), ('PR', 'Puerto Rico '), ('ME', 'Maine '), ('NJ', 'New Jersey '), ('WV', 'West Virginia '), ('WA', 'Washington '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Africa '), ('AL', 'Alabama '), ('RI', 'Rhode Island ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', "I'm not sure")], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('place_of_worship', 'Place of worship'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('workplace', 'Workplace or potential workplace')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('prevented_from_service', 'Prevented from using a service or service terminated'), ('vote', 'Ability to vote was impacted'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('discriminated_against', 'Otherwise discriminated against'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_access', 'Denied access or removed from a location (including segregation)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility'), ('private_facility', 'Private facility'), ('not_sure', 'Not sure')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('public', 'Public -- Schools or programs funded by local, state, or the federal government'), ('not_sure', "I'm not sure"), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('undisclosed', 'I prefer not to disclose'), ('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('NC', 'North Carolina '), ('OH', 'Ohio '), ('SC', 'South Carolina '), ('VI', 'Virgin Islands '), ('VA', 'Virginia '), ('AP', 'Armed Forces Pacific '), ('AZ', 'Arizona '), ('SD', 'South Dakota '), ('OK', 'Oklahoma '), ('NY', 'New York '), ('OR', 'Oregon '), ('KY', 'Kentucky '), ('TX', 'Texas '), ('MD', 'Maryland '), ('AE', 'Armed Forces Middle East '), ('ND', 'North Dakota '), ('IL', 'Illinois '), ('CO', 'Colorado '), ('NH', 'New Hampshire '), ('NV', 'Nevada '), ('CT', 'Connecticut '), ('ID', 'Idaho '), ('AA', 'Armed Forces Americas '), ('AE', 'Armed Forces Canada '), ('GA', 'Georgia '), ('MT', 'Montana '), ('MO', 'Missouri '), ('LA', 'Louisiana '), ('DE', 'Delaware '), ('AS', 'American Samoa '), ('AK', 'Alaska '), ('IA', 'Iowa '), ('WY', 'Wyoming '), ('TN', 'Tennessee '), ('HI', 'Hawaii '), ('VT', 'Vermont '), ('CA', 'California '), ('KS', 'Kansas '), ('DC', 'District of Columbia '), ('AR', 'Arkansas '), ('NE', 'Nebraska '), ('NM', 'New Mexico '), ('MI', 'Michigan '), ('UT', 'Utah '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('MA', 'Massachusetts '), ('MS', 'Mississippi '), ('MN', 'Minnesota '), ('WI', 'Wisconsin '), ('IN', 'Indiana '), ('PA', 'Pennsylvania '), ('FL', 'Florida '), ('PR', 'Puerto Rico '), ('ME', 'Maine '), ('NJ', 'New Jersey '), ('WV', 'West Virginia '), ('WA', 'Washington '), ('AE', 'Armed Forces Europe '), ('AE', 'Armed Forces Africa '), ('AL', 'Alabama '), ('RI', 'Rhode Island ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('employer', 'Employer or potential employer'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('lender', 'Bank or loaning service'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_3_years', 'Within the last 3 years'), ('last_6_months', 'Within the last 6 months')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('employer', 'Employer or potential employer'), ('healthcare', 'Healthcare provider or staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff')], default=None, max_length=100),
        ),
    ]
