# Generated by Django 2.2.4 on 2019-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0025_auto_20190821_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='who_reporting_for',
        ),
        migrations.AddField(
            model_name='report',
            name='who_reporting_about',
            field=models.CharField(choices=[('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('Individual(s) from school or educational program (teacher, administrator, staff, or students)', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('SC', 'South Carolina '), ('ID', 'Idaho '), ('SD', 'South Dakota '), ('VA', 'Virginia '), ('WY', 'Wyoming '), ('MD', 'Maryland '), ('NJ', 'New Jersey '), ('KY', 'Kentucky '), ('MP', 'Northern Mariana Islands '), ('MN', 'Minnesota '), ('WV', 'West Virginia '), ('VT', 'Vermont '), ('ME', 'Maine '), ('PA', 'Pennsylvania '), ('WI', 'Wisconsin '), ('AE', 'Armed Forces Middle East '), ('MI', 'Michigan '), ('AS', 'American Samoa '), ('UT', 'Utah '), ('AL', 'Alabama '), ('RI', 'Rhode Island '), ('TX', 'Texas '), ('GU', 'Guam '), ('WA', 'Washington '), ('NV', 'Nevada '), ('GA', 'Georgia '), ('IN', 'Indiana '), ('MS', 'Mississippi '), ('AE', 'Armed Forces Europe '), ('DE', 'Delaware '), ('IL', 'Illinois '), ('OH', 'Ohio '), ('TN', 'Tennessee '), ('HI', 'Hawaii '), ('LA', 'Louisiana '), ('FL', 'Florida '), ('PR', 'Puerto Rico '), ('NY', 'New York '), ('MA', 'Massachusetts '), ('AK', 'Alaska '), ('NM', 'New Mexico '), ('CO', 'Colorado '), ('NC', 'North Carolina '), ('AE', 'Armed Forces Africa '), ('OK', 'Oklahoma '), ('AA', 'Armed Forces Americas '), ('VI', 'Virgin Islands '), ('MT', 'Montana '), ('AP', 'Armed Forces Pacific '), ('MO', 'Missouri '), ('CA', 'California '), ('AZ', 'Arizona '), ('AR', 'Arkansas '), ('IA', 'Iowa '), ('CT', 'Connecticut '), ('KS', 'Kansas '), ('NH', 'New Hampshire '), ('DC', 'District of Columbia '), ('NE', 'Nebraska '), ('OR', 'Oregon '), ('AE', 'Armed Forces Canada '), ('ND', 'North Dakota ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('no', 'No'), ('yes', 'Yes')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('workplace', 'Workplace or potential workplace'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('place_of_worship', 'Place of worship'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('voting', 'Voting location or ballot (including mail-in ballots)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility'), ('private_facility', 'Private facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('not_sure', 'Not sure'), ('federal_facility', 'Federal facility'), ('state_local_facility', 'State or local facility'), ('private_facility', 'Private facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(choices=[('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('SC', 'South Carolina '), ('ID', 'Idaho '), ('SD', 'South Dakota '), ('VA', 'Virginia '), ('WY', 'Wyoming '), ('MD', 'Maryland '), ('NJ', 'New Jersey '), ('KY', 'Kentucky '), ('MP', 'Northern Mariana Islands '), ('MN', 'Minnesota '), ('WV', 'West Virginia '), ('VT', 'Vermont '), ('ME', 'Maine '), ('PA', 'Pennsylvania '), ('WI', 'Wisconsin '), ('AE', 'Armed Forces Middle East '), ('MI', 'Michigan '), ('AS', 'American Samoa '), ('UT', 'Utah '), ('AL', 'Alabama '), ('RI', 'Rhode Island '), ('TX', 'Texas '), ('GU', 'Guam '), ('WA', 'Washington '), ('NV', 'Nevada '), ('GA', 'Georgia '), ('IN', 'Indiana '), ('MS', 'Mississippi '), ('AE', 'Armed Forces Europe '), ('DE', 'Delaware '), ('IL', 'Illinois '), ('OH', 'Ohio '), ('TN', 'Tennessee '), ('HI', 'Hawaii '), ('LA', 'Louisiana '), ('FL', 'Florida '), ('PR', 'Puerto Rico '), ('NY', 'New York '), ('MA', 'Massachusetts '), ('AK', 'Alaska '), ('NM', 'New Mexico '), ('CO', 'Colorado '), ('NC', 'North Carolina '), ('AE', 'Armed Forces Africa '), ('OK', 'Oklahoma '), ('AA', 'Armed Forces Americas '), ('VI', 'Virgin Islands '), ('MT', 'Montana '), ('AP', 'Armed Forces Pacific '), ('MO', 'Missouri '), ('CA', 'California '), ('AZ', 'Arizona '), ('AR', 'Arkansas '), ('IA', 'Iowa '), ('CT', 'Connecticut '), ('KS', 'Kansas '), ('NH', 'New Hampshire '), ('DC', 'District of Columbia '), ('NE', 'Nebraska '), ('OR', 'Oregon '), ('AE', 'Armed Forces Canada '), ('ND', 'North Dakota ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('employer', 'Employer or potential employer'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('lender', 'Bank or loaning service'), ('healthcare', 'Healthcare provider or staff'), ('landlord', 'Landlord, leasing office, or home/rental provider')], default=None, max_length=100, null=True),
        ),
    ]
