# Generated by Django 2.2.4 on 2019-08-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0026_auto_20190821_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='who_reporting_about',
        ),
        migrations.AddField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('myself', "I'm reporting for myself"), ('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('WV', 'West Virginia '), ('MN', 'Minnesota '), ('OK', 'Oklahoma '), ('SC', 'South Carolina '), ('CO', 'Colorado '), ('IA', 'Iowa '), ('NH', 'New Hampshire '), ('MO', 'Missouri '), ('AP', 'Armed Forces Pacific '), ('SD', 'South Dakota '), ('PR', 'Puerto Rico '), ('CT', 'Connecticut '), ('NE', 'Nebraska '), ('RI', 'Rhode Island '), ('UT', 'Utah '), ('MS', 'Mississippi '), ('NC', 'North Carolina '), ('AE', 'Armed Forces Canada '), ('MI', 'Michigan '), ('ID', 'Idaho '), ('PA', 'Pennsylvania '), ('NM', 'New Mexico '), ('FL', 'Florida '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('NJ', 'New Jersey '), ('ND', 'North Dakota '), ('AL', 'Alabama '), ('CA', 'California '), ('VI', 'Virgin Islands '), ('DC', 'District of Columbia '), ('MD', 'Maryland '), ('WA', 'Washington '), ('AZ', 'Arizona '), ('OH', 'Ohio '), ('AA', 'Armed Forces Americas '), ('MA', 'Massachusetts '), ('VA', 'Virginia '), ('OR', 'Oregon '), ('WY', 'Wyoming '), ('AE', 'Armed Forces Africa '), ('NY', 'New York '), ('AE', 'Armed Forces Middle East '), ('GA', 'Georgia '), ('TN', 'Tennessee '), ('TX', 'Texas '), ('HI', 'Hawaii '), ('AE', 'Armed Forces Europe '), ('MT', 'Montana '), ('ME', 'Maine '), ('IN', 'Indiana '), ('LA', 'Louisiana '), ('VT', 'Vermont '), ('AK', 'Alaska '), ('AR', 'Arkansas '), ('DE', 'Delaware '), ('KY', 'Kentucky '), ('WI', 'Wisconsin '), ('AS', 'American Samoa '), ('NV', 'Nevada '), ('IL', 'Illinois '), ('KS', 'Kansas ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('not_sure', "I'm not sure")], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('workplace', 'Workplace or potential workplace'), ('place_of_worship', 'Place of worship'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('discriminated_against', 'Otherwise discriminated against'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('denied_housing', 'Denied housing or subjected to harmful living conditions'), ('denied_access', 'Denied access or removed from a location (including segregation)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('state_local_facility', 'State or local facility'), ('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('state_local_facility', 'State or local facility'), ('not_sure', 'Not sure'), ('private_facility', 'Private facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(choices=[('parent_guardian', 'Im a parent or guardian of the person affected'), ('witness to the situation', 'Im a witness to the situation'), ('professional', 'Im providing professional assistance')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('WV', 'West Virginia '), ('MN', 'Minnesota '), ('OK', 'Oklahoma '), ('SC', 'South Carolina '), ('CO', 'Colorado '), ('IA', 'Iowa '), ('NH', 'New Hampshire '), ('MO', 'Missouri '), ('AP', 'Armed Forces Pacific '), ('SD', 'South Dakota '), ('PR', 'Puerto Rico '), ('CT', 'Connecticut '), ('NE', 'Nebraska '), ('RI', 'Rhode Island '), ('UT', 'Utah '), ('MS', 'Mississippi '), ('NC', 'North Carolina '), ('AE', 'Armed Forces Canada '), ('MI', 'Michigan '), ('ID', 'Idaho '), ('PA', 'Pennsylvania '), ('NM', 'New Mexico '), ('FL', 'Florida '), ('GU', 'Guam '), ('MP', 'Northern Mariana Islands '), ('NJ', 'New Jersey '), ('ND', 'North Dakota '), ('AL', 'Alabama '), ('CA', 'California '), ('VI', 'Virgin Islands '), ('DC', 'District of Columbia '), ('MD', 'Maryland '), ('WA', 'Washington '), ('AZ', 'Arizona '), ('OH', 'Ohio '), ('AA', 'Armed Forces Americas '), ('MA', 'Massachusetts '), ('VA', 'Virginia '), ('OR', 'Oregon '), ('WY', 'Wyoming '), ('AE', 'Armed Forces Africa '), ('NY', 'New York '), ('AE', 'Armed Forces Middle East '), ('GA', 'Georgia '), ('TN', 'Tennessee '), ('TX', 'Texas '), ('HI', 'Hawaii '), ('AE', 'Armed Forces Europe '), ('MT', 'Montana '), ('ME', 'Maine '), ('IN', 'Indiana '), ('LA', 'Louisiana '), ('VT', 'Vermont '), ('AK', 'Alaska '), ('AR', 'Arkansas '), ('DE', 'Delaware '), ('KY', 'Kentucky '), ('WI', 'Wisconsin '), ('AS', 'American Samoa '), ('NV', 'Nevada '), ('IL', 'Illinois '), ('KS', 'Kansas ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('employer', 'Employer or potential employer'), ('lender', 'Bank or loaning service'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('healthcare', 'Healthcare provider or staff')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('greater_than_3_years', 'More than 3 years ago'), ('last_6_months', 'Within the last 6 months'), ('last_3_years', 'Within the last 3 years')], default=None, max_length=700),
        ),
    ]
