# Generated by Django 2.2.4 on 2019-12-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0026_insert_and_reorder_protected_class'),
        ('cts_forms', '0025_make_hatecrimes_question_optional'),
    ]

    operations = [
    ]
