# Generated by Django 2.2.4 on 2019-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0027_auto_20190821_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_state',
            field=models.CharField(blank=True, choices=[('AA', 'Armed Forces Americas '), ('DC', 'District of Columbia '), ('DE', 'Delaware '), ('LA', 'Louisiana '), ('IL', 'Illinois '), ('MN', 'Minnesota '), ('WV', 'West Virginia '), ('HI', 'Hawaii '), ('OK', 'Oklahoma '), ('SD', 'South Dakota '), ('GA', 'Georgia '), ('OR', 'Oregon '), ('NM', 'New Mexico '), ('CO', 'Colorado '), ('GU', 'Guam '), ('AE', 'Armed Forces Europe '), ('RI', 'Rhode Island '), ('NV', 'Nevada '), ('CT', 'Connecticut '), ('MS', 'Mississippi '), ('ND', 'North Dakota '), ('NY', 'New York '), ('TN', 'Tennessee '), ('WI', 'Wisconsin '), ('AK', 'Alaska '), ('MT', 'Montana '), ('KY', 'Kentucky '), ('FL', 'Florida '), ('VA', 'Virginia '), ('WY', 'Wyoming '), ('AS', 'American Samoa '), ('AE', 'Armed Forces Canada '), ('KS', 'Kansas '), ('NJ', 'New Jersey '), ('NE', 'Nebraska '), ('OH', 'Ohio '), ('SC', 'South Carolina '), ('MO', 'Missouri '), ('MP', 'Northern Mariana Islands '), ('AL', 'Alabama '), ('AZ', 'Arizona '), ('NH', 'New Hampshire '), ('WA', 'Washington '), ('AE', 'Armed Forces Middle East '), ('ME', 'Maine '), ('MD', 'Maryland '), ('VT', 'Vermont '), ('ID', 'Idaho '), ('NC', 'North Carolina '), ('AR', 'Arkansas '), ('PA', 'Pennsylvania '), ('IN', 'Indiana '), ('MI', 'Michigan '), ('MA', 'Massachusetts '), ('TX', 'Texas '), ('PR', 'Puerto Rico '), ('VI', 'Virgin Islands '), ('AP', 'Armed Forces Pacific '), ('IA', 'Iowa '), ('AE', 'Armed Forces Africa '), ('UT', 'Utah '), ('CA', 'California ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('no', 'No'), ('yes', 'Yes')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(choices=[('store', 'Retail/commercial building (store, restaurant, hotel, nightclub, theater, gym, or other commercial space)'), ('place_of_worship', 'Place of worship'), ('public_space', 'Outdoor public space (including car, street, sidewalk, park)'), ('school', 'Educational institution (school, university), education program or educational activity (after school program or workshop)'), ('workplace', 'Workplace or potential workplace'), ('voting', 'Voting location or ballot (including mail-in ballots)'), ('government_building', 'Another government building (courthouse, DMV, post office)'), ('home,', 'Home, potential home, or services to help with purchasing a home (banks, lenders, or other financial services)'), ('healthcare', 'Healthcare facility (including mental health or long-term care)'), ('incarcerated', 'Prison, jail, or juvenile corrections facility, or while otherwise incarcerated')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('harassed', 'Harassed, threatened, assaulted, or otherwise made to feel unsafe (including sexual harassment or assault)'), ('vote', 'Ability to vote was impacted'), ('retaliated', 'Retaliated against or otherwise mistreated for reporting an issue'), ('prevented_from_service', 'Prevented from using a service or service terminated'), ('denied_access', 'Denied access or removed from a location (including segregation)'), ('fired', 'Fired, not hired, demoted, or asked to show more documentation than required'), ('discriminated_against', 'Otherwise discriminated against'), ('denied_housing', 'Denied housing or subjected to harmful living conditions')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('private_employer', 'Private employer -- Businesses or non-profits not funded by the government such as retail stores, banks, or restaurants.'), ('public_employer', 'Public employer -- Funded by the government like a post office, fire department, courthouse, DMV, or public school. This could be at the local, state, or federal level.'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_facility',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_healthcare',
            field=models.CharField(choices=[('private_facility', 'Private facility'), ('not_sure', 'Not sure'), ('state_local_facility', 'State or local facility'), ('federal_facility', 'Federal facility')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('not_sure', "I'm not sure"), ('private', 'Private -- Schools or programs funded privately such as charter schools, magnet schools, or faith-based colleges'), ('public', 'Public -- Schools or programs funded by local, state, or the federal government')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(choices=[('parent_guardian', 'Im a parent or guardian of the person affected'), ('professional', 'Im providing professional assistance'), ('witness to the situation', 'Im a witness to the situation')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_state',
            field=models.CharField(blank=True, choices=[('AA', 'Armed Forces Americas '), ('DC', 'District of Columbia '), ('DE', 'Delaware '), ('LA', 'Louisiana '), ('IL', 'Illinois '), ('MN', 'Minnesota '), ('WV', 'West Virginia '), ('HI', 'Hawaii '), ('OK', 'Oklahoma '), ('SD', 'South Dakota '), ('GA', 'Georgia '), ('OR', 'Oregon '), ('NM', 'New Mexico '), ('CO', 'Colorado '), ('GU', 'Guam '), ('AE', 'Armed Forces Europe '), ('RI', 'Rhode Island '), ('NV', 'Nevada '), ('CT', 'Connecticut '), ('MS', 'Mississippi '), ('ND', 'North Dakota '), ('NY', 'New York '), ('TN', 'Tennessee '), ('WI', 'Wisconsin '), ('AK', 'Alaska '), ('MT', 'Montana '), ('KY', 'Kentucky '), ('FL', 'Florida '), ('VA', 'Virginia '), ('WY', 'Wyoming '), ('AS', 'American Samoa '), ('AE', 'Armed Forces Canada '), ('KS', 'Kansas '), ('NJ', 'New Jersey '), ('NE', 'Nebraska '), ('OH', 'Ohio '), ('SC', 'South Carolina '), ('MO', 'Missouri '), ('MP', 'Northern Mariana Islands '), ('AL', 'Alabama '), ('AZ', 'Arizona '), ('NH', 'New Hampshire '), ('WA', 'Washington '), ('AE', 'Armed Forces Middle East '), ('ME', 'Maine '), ('MD', 'Maryland '), ('VT', 'Vermont '), ('ID', 'Idaho '), ('NC', 'North Carolina '), ('AR', 'Arkansas '), ('PA', 'Pennsylvania '), ('IN', 'Indiana '), ('MI', 'Michigan '), ('MA', 'Massachusetts '), ('TX', 'Texas '), ('PR', 'Puerto Rico '), ('VI', 'Virgin Islands '), ('AP', 'Armed Forces Pacific '), ('IA', 'Iowa '), ('AE', 'Armed Forces Africa '), ('UT', 'Utah '), ('CA', 'California ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(choices=[('lender', 'Bank or loaning service'), ('employer', 'Employer or potential employer'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('healthcare', 'Healthcare provider or staff'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('landlord', 'Landlord, leasing office, or home/rental provider')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='when',
            field=models.CharField(choices=[('last_3_years', 'Within the last 3 years'), ('greater_than_3_years', 'More than 3 years ago'), ('last_6_months', 'Within the last 6 months')], default=None, max_length=700),
        ),
        migrations.AlterField(
            model_name='report',
            name='who_reporting_for',
            field=models.CharField(choices=[('another', "I'm reporting on behalf of another person"), ('undisclosed', 'I prefer not to disclose'), ('myself', "I'm reporting for myself")], default=None, max_length=100, null=True),
        ),
    ]
