# Generated by Django 2.2.8 on 2019-12-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0028_add_election_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_section',
            field=models.TextField(choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability'), ('ELS', 'Employment Litigation Services'), ('EOS', 'Education'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing'), ('IER', 'Immigrant and Employee Rights'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default='ADM'),
        ),
    ]
