# Generated by Django 2.2.4 on 2020-01-07 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0029_alphabetize_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='how_many',
        ),
        migrations.RemoveField(
            model_name='report',
            name='when',
        ),
        migrations.AddField(
            model_name='report',
            name='last_incident_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(31, message='Day value too high')),
        ),
        migrations.AddField(
            model_name='report',
            name='last_incident_month',
            field=models.PositiveIntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(default=2019, verbose_name=django.core.validators.MaxValueValidator(2020)),
            preserve_default=False,
        ),
    ]
