# Generated by Django 2.2.8 on 2020-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0029_alphabetize_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='servicemember',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protectedclass',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('disability', 'Disability (including temporary or recovery)'), ('race', 'Race/color'), ('origin', 'National origin (including ancestry and ethnicity)'), ('immigration', 'Immigration/citizenship status (choosing this will not share your status)'), ('religion', 'Religion'), ('gender', 'Sex or gender identity (including gender stereotypes) or pregnancy'), ('orientation', 'Sexual orientation'), ('family', 'Family, marriage, or parental status'), ('military', 'Military status'), ('age', 'Age'), ('genetic', 'Genetic information'), ('language', 'Language'), ('other', 'Other reason'), ('none', 'None of these apply to me')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hatecrimes_trafficking',
            field=models.ManyToManyField(blank=True, to='cts_forms.HateCrimesandTrafficking'),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(choices=[('public_employer', 'Public employer'), ('private_employer', 'Private employer'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
    ]
