# Generated by Django 2.2.8 on 2020-01-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0030_add_servicemembers'),
        ('cts_forms', '0030_add_incident_date_remove_old_fields'),
    ]

    operations = [
    ]
