# Generated by Django 2.2.8 on 2020-01-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0030_auto_20200108_1928'),
        ('cts_forms', '0030_add_incident_date_remove_old_fields'),
    ]

    operations = [
    ]
