# Generated by Django 2.2.4 on 2019-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0030_auto_20190821_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='respondent_type',
            field=models.CharField(blank=True, choices=[('employer', 'Employer or potential employer'), ('landlord', 'Landlord, leasing office, or home/rental provider'), ('police_corrections_staff', 'Police, prison guard, or other corrections staff'), ('other_public_official', 'Other public official (judge, voting official, or other government official)'), ('school', 'Individual(s) from school or educational program (teacher, administrator, staff, or students)'), ('healthcare', 'Healthcare provider or staff'), ('lender', 'Bank or loaning service')], default=None, max_length=100, null=True),
        ),
    ]
