# Generated by Django 2.2.4 on 2019-08-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0031_auto_20190821_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, choices=[('parent_guardian', 'Im a parent or guardian of the person affected'), ('professional', 'Im providing professional assistance'), ('witness to the situation', 'Im a witness to the situation')], default=None, max_length=100, null=True),
        ),
    ]
