# Generated by Django 2.2.8 on 2020-01-16 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0031_merge_20200116_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hatecrimes_trafficking',
            field=models.ManyToManyField(blank=True, to='cts_forms.HateCrimesandTrafficking'),
        ),
        migrations.AlterField(
            model_name='report',
            name='inside_correctional_facility',
            field=models.CharField(choices=[('outside', 'Outside a prison or correctional facility'), ('inside', 'Inside a prison or correctional facility')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_month',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(12, message='Month must be 12 or less')),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(2020, message='Date must not be in the future')),
        ),
    ]
