# Generated by Django 2.2.8 on 2020-01-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0031_add_location_fields'),
        ('cts_forms', '0032_auto_20200116_2255'),
    ]

    operations = [
    ]
