# Generated by Django 2.2.4 on 2019-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0032_auto_20190821_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='how_many',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('not_sure', "I'm not sure"), ('yes', 'Yes')], default=None, max_length=700, null=True),
        ),
    ]
