# Generated by Django 2.2.8 on 2020-01-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0033_merge_20200121_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='election_details',
            field=models.CharField(blank=True, choices=[('federal', 'Federal'), ('state_local', 'State or local'), ('both', 'Both'), ('unknown', "I'm not sure")], max_length=225, null=True),
        ),
    ]
