# Generated by Django 2.2.9 on 2020-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0036_update_commercial_public_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(choices=[('public', 'Public school or educational program'), ('private', 'Private school or educational program'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
    ]
