# Generated by Django 2.2.9 on 2020-02-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0037_update_education_location_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalhistory',
            name='author',
            field=models.CharField(default='anonymous', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalhistory',
            name='note',
            field=models.CharField(max_length=1000),
        ),
    ]
