# Generated by Django 2.2.9 on 2020-02-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0038_add_author_to_internalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='internal_comments',
            field=models.ManyToManyField(blank=True, to='cts_forms.InternalHistory'),
        ),
    ]
