# Generated by Django 2.2.9 on 2020-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0039_add_comments_to_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='respondent_name',
            new_name='contact_address_line_1',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='respondent_city',
            new_name='contact_city',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='respondent_state',
            new_name='contact_state',
        ),
        migrations.RemoveField(
            model_name='report',
            name='respondent_contact_ask',
        ),
        migrations.RemoveField(
            model_name='report',
            name='respondent_type',
        ),
        migrations.AddField(
            model_name='report',
            name='contact_address_line_2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
