# Generated by Django 2.2.9 on 2020-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0040_new_contact_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatecrimesandtrafficking',
            name='hatecrimes_trafficking_option',
            field=models.CharField(blank=True, choices=[('physical_harm', 'Physical harm or threats of violence based on race, color, national origin, religion, gender, sexual orientation, gender identity, or disability'), ('trafficking', 'Coerced or forced to do work or perform a sex act in exchange for something of value')], max_length=500, null=True, unique=True),
        ),
    ]
