# Generated by Django 2.2.9 on 2020-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0043_update_trafficking_data_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedclass',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='protectedclass',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('age', 'Age'), ('disability', 'Disability (including temporary or recovery)'), ('family_status', 'Family, marital, or parental status'), ('gender', 'Gender identity (including gender stereotypes)'), ('genetic', 'Genetic information (including family medical history)'), ('immigration', 'Immigration/citizenship status (choosing this will not share your status)'), ('language', 'Language'), ('national_origin', 'National origin (including ancestry and ethnicity)'), ('pregnancy', 'Pregnancy'), ('race/color', 'Race/color'), ('religion', 'Religion'), ('sex', 'Sex'), ('orientation', 'Sexual orientation'), ('none', 'None of these apply to me'), ('other', 'Other')], max_length=100, null=True, unique=True),
        ),
    ]
