# Generated by Django 2.2.9 on 2020-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0046_update_primary_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
