# Generated by Django 2.2.9 on 2020-02-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0049_fix_other_duplicates'),
        ('cts_forms', 'update_primary_complaint'),
    ]

    operations = [
    ]
