# Generated by Django 2.2.10 on 2020-03-06 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0051_add_modified_date_and_alter_protected_class'),
    ]

    operations = [
        # Taking out the last fields from the prototype
        migrations.RemoveField(
            model_name='report',
            name='public_or_private_facility',
        ),
        migrations.RemoveField(
            model_name='report',
            name='public_or_private_healthcare',
        ),
        # New fields for Proform
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='crt_reciept_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(31)),
        ),
        migrations.AddField(
            model_name='report',
            name='crt_reciept_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(12)),
        ),
        migrations.AddField(
            model_name='report',
            name='crt_reciept_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2020)),
        ),
        migrations.AddField(
            model_name='report',
            name='intake_format',
            field=models.CharField(choices=[('web', 'web'), ('letter', 'letter'), ('phone', 'phone'), ('fax', 'fax')], default=None, max_length=100, null=True),
        ),
        # Making fields optional for Proform
        migrations.AlterField(
            model_name='report',
            name='correctional_facility_type',
            field=models.CharField(blank=True, choices=[('state_local', 'State/local'), ('federal', 'Federal'), ('private', 'Private'), ('not_sure', "I'm not sure")], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='election_details',
            field=models.CharField(blank=True, choices=[('federal', 'Federal'), ('state_local', 'State or local'), ('both', 'Both'), ('unknown', "I'm not sure")], default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='inside_correctional_facility',
            field=models.CharField(blank=True, choices=[('outside', 'Outside a prison or correctional facility'), ('inside', 'Inside a prison or correctional facility')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(12, message='Month must be 12 or less')),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2020, message='Date must not be in the future')),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_city_town',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands'), ('AE', 'Armed Forces Africa'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Canada'), ('AE', 'Armed Forces Europe'), ('AE', 'Armed Forces Middle East'), ('AP', 'Armed Forces Pacific')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='other_commercial_or_public_place',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='protected_class',
            field=models.ManyToManyField(blank=True, to='cts_forms.ProtectedClass'),
        ),
        migrations.AlterField(
            model_name='report',
            name='servicemember',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='violation_summary',
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
    ]
