# Generated by Django 2.2.10 on 2020-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0052_proform_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='intake_format',
            field=models.CharField(choices=[('web', 'web'), ('letter', 'letter'), ('phone', 'phone'), ('fax', 'fax'), ('email', 'email')], default=None, max_length=100, null=True),
        ),
    ]
