# Generated by Django 2.2.11 on 2020-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0054_report_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatecrimesandtrafficking',
            name='hatecrimes_trafficking_option',
            field=models.CharField(blank=True, choices=[('physical_harm', 'Physical harm or threats of violence based on race, color, national origin, religion, gender, sexual orientation, gender identity, or disability'), ('trafficking', 'Threatened, forced, and held against your will for the purposes of performing work or commercial sex acts. This could include threats of physical harm, withholding promised wages, or being held under a false work contract')], max_length=500, null=True, unique=True),
        ),
    ]
