# Generated by Django 2.2.11 on 2020-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0055_rename_CommentAndSummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentandsummary',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentandsummary',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
