# Generated by Django 2.2.11 on 2020-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0057_longer_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='internal_comments',
            field=models.ManyToManyField(to='cts_forms.CommentAndSummary'),
        ),
    ]
