# Generated by Django 2.2.11 on 2020-03-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0056_update_trafficking_text'),
        ('cts_forms', '0058_no_blank_comment'),
    ]

    operations = [
    ]
