# Generated by Django 2.2.12 on 2020-04-30 18:00

from django.db import migrations

from cts_forms.model_variables import (HATE_CRIMES_TRAFFICKING_MODEL_CHOICES,
                                       PROTECTED_MODEL_CHOICES)


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0066_auto_20200430_1400'),
    ]

    def forward(apps, schema_editor):
        """
        Set value field of existing HateCrimesandTrafficking and ProtectedClass instances
        to those matching their labels set in orignal field
        """
        HateCrimesandTrafficking = apps.get_model('cts_forms', 'HateCrimesandTrafficking')
        ProtectedClass = apps.get_model('cts_forms', 'ProtectedClass')

        hc_labels = {label: value for value, label in HATE_CRIMES_TRAFFICKING_MODEL_CHOICES}

        for hc in HateCrimesandTrafficking.objects.all():
            hc.value = hc_labels[hc.hatecrimes_trafficking_option]
            hc.save()

        pc_labels = {label: value for value, label in PROTECTED_MODEL_CHOICES}
        for pc in ProtectedClass.objects.all():
            pc.value = pc_labels[pc.protected_class]
            pc.save()


    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forward),
    ]
