# Generated by Django 2.2.12 on 2020-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0067_populate_new_choice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatecrimesandtrafficking',
            name='value',
            field=models.CharField(blank=True, choices=[('physical_harm', 'Physical harm or threats of violence based on race, color, national origin, religion, gender, sexual orientation, gender identity, or disability'), ('trafficking', 'Threatened, forced, and held against your will for the purposes of performing work or commercial sex acts. This could include threats of physical harm, withholding promised wages, or being held under a false work contract')], max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='protectedclass',
            name='value',
            field=models.CharField(blank=True, choices=[('age', 'Age'), ('disability', 'Disability (including temporary or recovery)'), ('family_status', 'Family, marital, or parental status'), ('gender', 'Gender identity (including gender stereotypes)'), ('genetic', 'Genetic information (including family medical history)'), ('immigration', 'Immigration/citizenship status (choosing this will not share your status)'), ('language', 'Language'), ('national_origin', 'National origin (including ancestry and ethnicity)'), ('pregnancy', 'Pregnancy'), ('race/color', 'Race/color'), ('religion', 'Religion'), ('sex', 'Sex'), ('orientation', 'Sexual orientation'), ('none', 'None of these apply to me'), ('other', 'Other reason')], max_length=100, unique=True),
        ),
    ]
