# Generated by Django 2.2.12 on 2020-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0068_new_choice_fields_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='inside_correctional_facility',
            field=models.CharField(blank=True, choices=[('outside', 'No'), ('inside', 'Yes')], default=None, max_length=255, null=True),
        ),
    ]
