# Generated by Django 2.2.12 on 2020-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0068_new_choice_fields_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='commercial_or_public_place',
            field=models.CharField(blank=True, choices=[('place_of_worship', 'Place of worship or about a place of worship'), ('store', 'Commercial or retail building'), ('healthcare', 'Healthcare facility'), ('financial', 'Financial institution'), ('public_space', 'Public space'), ('other', 'Other')], default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='employer_size',
            field=models.CharField(blank=True, choices=[('14_or_less', 'Fewer than 15 employees'), ('15_or_more', '15 or more employees'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='inside_correctional_facility',
            field=models.CharField(blank=True, choices=[('outside', 'No'), ('inside', 'Yes')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_employer',
            field=models.CharField(blank=True, choices=[('public_employer', 'Public employer'), ('private_employer', 'Private employer'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_or_private_school',
            field=models.CharField(blank=True, choices=[('public', 'Public school or educational program'), ('private', 'Private school or educational program'), ('not_sure', "I'm not sure")], default=None, max_length=100, null=True),
        ),
    ]
