# Generated by Django 2.2.12 on 2020-05-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0069_allow_blanks_for_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('workplace', 'Workplace discrimination or other employment-related problem'), ('housing', 'Housing discrimination or harassment'), ('education', 'Discrimination at a school, educational program or service, or related to receiving education'), ('voting', 'Voting rights or ability to vote affected'), ('police', 'Mistreated by police, or correctional staff (including while in prison)'), ('commercial_or_public', 'Discriminated against in a commercial location or public place'), ('something_else', 'Something else happened')], default='', max_length=100),
        ),
    ]
