# Generated by Django 2.2.12 on 2020-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0070_update_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hate_crime',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
    ]
