# Generated by Django 2.2.12 on 2020-05-26 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0071_report_hate_crime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=225, null=True, validators=[django.core.validators.RegexValidator('^(?=^\\D*(\\d\\D*){7,15}$)(?=^(?:(?![a-zA-Z]).)*$).*$', message='If you submit a phone number, please make sure to include between 7 and 15 digits. The characters "+", ")", "(", "-", and "." are allowed. Please include country code if entering an international phone number.')]),
        ),
    ]
