# Generated by Django 2.2.13 on 2020-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0076_auto_20200616_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='crt_date_closed',
            field=models.DateTimeField(blank=True, help_text='The Date this report\'s status was most recently set to "Closed"', null=True),
        ),
    ]
