# Generated by Django 2.2.13 on 2020-07-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0077_report_add_date_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentandsummary',
            options={'verbose_name_plural': 'Comments and summaries'},
        ),
        migrations.AlterModelOptions(
            name='hatecrimesandtrafficking',
            options={'verbose_name': 'Hate crime and trafficking', 'verbose_name_plural': 'Hate crimes and trafficking'},
        ),
        migrations.AlterModelOptions(
            name='protectedclass',
            options={'verbose_name_plural': 'Protected classes'},
        ),
    ]
