# Generated by Django 2.2.13 on 2020-06-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0078_tweak_response_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='crt_date_closed',
            new_name='closed_date',
        ),
    ]
