# Generated by Django 2.2.12 on 2020-06-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0079_rename_date_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsetemplate',
            old_name='template',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='responsetemplate',
            old_name='description',
            new_name='subject',
        ),
    ]
