# Generated by Django 2.2.13 on 2020-06-29 22:56

from django.db import migrations


def tweak_templates(apps, schema_editor):
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    nonactionable = ResponseTemplate.objects.get(title='Non-Actionable')
    # adjust subject line
    nonactionable.subject = "Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }}"
    nonactionable.save()

    nocapacity = ResponseTemplate.objects.get(title='No capacity')
    # adjust subject line
    nocapacity.subject = "Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }}"
    nocapacity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0080_rename_response_subject_body'),
    ]

    operations = [
        migrations.RunPython(tweak_templates),
    ]
