# Generated by Django 2.2.13 on 2020-07-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0078_update_model_verbose_names'),
        ('cts_forms', '0081_form_template_subject_changes'),
    ]

    operations = [
    ]
