# Generated by Django 2.2.13 on 2020-07-02 22:03

from django.db import migrations


def add_templates(apps, schema_editor):
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    ResponseTemplate.objects.create(
        title='HCE - Referral for Housing/Lending/Public Accommodation',
        subject='Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }}',
        body="""
{{ addressee }},

You contacted the Department of Justice on {{ date_of_intake }}.

What we did:

Your report number is {{ record_locator }}.

Team members from the Civil Rights Division reviewed the information you submitted. Based on your report, our team determined that you alleged discrimination in one of more of the following areas:

1) housing;
2) public accommodations, such as hotels and restaurants; or
3) credit.

Please be aware that in situations involving these types of discrimination, the Civil Rights Division generally becomes involved only when groups of people are affected. We generally do not open investigations based on individual claims of discrimination.

With this in mind, we will carefully review your report and will contact you if we need additional information and/or are able to open an investigation.

What you can do:

If your report relates to discrimination in housing, the U.S. Department of Housing & Urban Development ("HUD") may be able to help. HUD is the agency responsible for reviewing housing complaints that affect only one person.

NOTE: There are strict time limits for filing complaints of housing discrimination. If you believe you have been discriminated against in housing, you should contact the appropriate agency as soon as possible.

I EXPERIENCED...

Housing discrimination based on:

- Race or color,
- National origin,
- Religion,
- Sex,
- Familial status,
- Disability, or
- Retaliation

AGENCY THAT MAY BE ABLE TO HELP:

U.S. Department of Housing and Urban Development (HUD)
Office of Fair Housing and Equal Opportunity

    File online: www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint

    Contact by phone: (800) 669-9777

    File in person at your nearest local office:
    www.hud.gov/program_offices/fair_housing_equal_opp/contact_fheo

I EXPERIENCED...

An issue with or have question about a:

- Housing subsidy or voucher:
- Public housing authority,
- Public housing authority employee, or
- Landlord receiving a housing subsidy

AGENCY THAT MAY BE ABLE TO HELP:

U.S. Department of Housing and Urban Development (HUD)
Public and Indian Housing

    PIH Customer Service Center:
    www.hud.gov/program_offices/public_indian_housing

    Contact by phone: (800) 955-2232

I EXPERIENCED...

An issue with or have a question about:

- Homelessness

AGENCY THAT MAY BE ABLE TO HELP:

U.S. Department of Housing and Urban Development
Resources on homelessness

    Find online:
    www.hudexchange.info/housing-and-homeless-assistance/

I EXPERIENCED...

Fraud, waste, or abuse related to:

- HUD, or
- a HUD-associated program

AGENCY THAT MAY BE ABLE TO HELP:

U.S. Department of Housing and Urban Development (HUD)
Office of Inspector General

    Find online:
    www.hudoig.gov/hotline

    Contact by email: hotline@hudoig.gov

If your report relates to discrimination in lending, you may want to file complaints with HUD and with the Consumer Financial Protection Bureau (CFPB).  These agencies are responsible for reviewing complaints that affect only one person.

NOTE: There are strict time limits for filing complaints of lending discrimination. If you believe you have been discriminated against in lending, you should contact the appropriate agency as soon as possible.

I EXPERIENCED...

Discrimination in home financing (i.e., mortgage) based on:

- Race or color,
- National origin,
- Religion,
- Sex,
- Familial status,
- Disability, or
- Retaliation

AGENCY THAT MAY BE ABLE TO HELP:

U.S. Department of Housing and Urban Development (HUD)
Office of Fair Housing and Equal Opportunity

    File online:
    www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint

    Contact by phone: (800) 669-9777

    File in person at your nearest local office:
    www.hud.gov/program_offices/fair_housing_equal_opp/contact_fheo

I EXPERIENCED...

Discrimination in home financing (i.e., mortgage) OR any other form of credit based on:

- Race or color,
- National origin,
- Religion,
- Sex,
- Marital status,
- Age (as long as you are old enough to enter a contract),
- Receiving income from any public assistance program, or
- Retaliation

AGENCY THAT MAY BE ABLE TO HELP:
Consumer Financial Protection Bureau (CFPB)

    File online:
    www.consumerfinance.gov/complaint/

    Contact by phone: (855) 411-2372

If your report relates to discrimination at public accommodations, including hotels, restaurants, theaters, and other places of entertainment, your state’s attorney general may be able to help.

NOTE: There may be time limits for filing complaints related to discrimination in public accommodations. If you believe you have been discriminated against, you should contact your state attorney general as soon as possible.

I EXPERIENCED...

Discrimination in public accommodation (hotels, restaurants, theaters, and places of entertainment) based on:

- Race or color,
- Religion, or
- National origin

AGENCY THAT MAY BE ABLE TO HELP:

State Attorneys General
    Find online: www.usa.gov/state-attorney-general
    Contact by phone: (844) 872-4681

In addition, your state bar association or local legal aid office may be able to help with your issue.

TO FIND...

A personal attorney

ORGANIZATION THAT MAY BE ABLE TO HELP:

American Bar Association
    Find online:
    www.findlegalhelp.org

    Contact by phone: (800) 285-2221

TO FIND...

A personal attorney for low-income individuals

ORGANIZATION THAT MAY BE ABLE TO HELP:

Legal Services Corporation (or Legal Aid Offices)

    Find online:
    www.lsc.gov/find-legal-aid

    Contact by phone: (202) 295-1500

How you helped:

Your report will help us advance civil rights. Information from reports such as yours helps us understand emerging and urgent issues in civil rights. This helps inform how we protect the civil rights of all people in this country.

Thank you for taking the time to contact the Department of Justice about your concerns.

Sincerely,

U.S. Department of Justice
Civil Rights Division
        """,
    )
    ResponseTemplate.objects.create(
        title='SPL - Referral for PREA Issues',
        subject='Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }}',
        body="""
{{ addressee }},

You contacted the Department of Justice on {{ date_of_intake }}.  Based on our review to this point, we want to make you aware that you may want to contact your state’s PREA Coordinator.

What we did:

Your record number is {{ record_locator }}.

Team members from the Civil Rights Division reviewed the information you submitted.  Based on your report, our team determined that you raised concerns involving sexual abuse or sexual harassment in detention.  This may fall under the Prison Rape Elimination Act (PREA). PREA is a law that makes it illegal to:

- sexually abuse or sexually harass prisoners and detainees; and
- retaliate against a prisoner or staff member who reports sexual abuse or sexual harassment.

We will continue to review your report and will contact you if we need additional information.  However, you should be aware that in situations involving sexual abuse or sexual harassment of prisoners and detainees, the Civil Rights Division can only become involved where there is a widespread pattern of misconduct.  Therefore, we generally cannot open investigations based on individual claims.

Accordingly, we want to make you aware that your state’s PREA Coordinator may be able to help in your situation.  A PREA Coordinator can investigate individual claims such as yours. To help you connect to your state’s PREA Coordinator, we have included a directory with this response.

What you can do:

Your state’s PREA Coordinator may be able to help in your situation. You can contact your state’s PREA Coordinator by referring to the attached directory.

You can also learn more about PREA at the PREA Information Center’s website: www.prearesourcecenter.org/training-technical-assistance/prea-101/prisons-and-jail-standards

How you helped:

Your report will help us advance civil rights. Information from reports such as yours helps us understand emerging trends and issues in civil rights. This helps inform how we protect the civil rights of all people in this country.

Thank you for taking the time to contact the Department of Justice about your concerns.

Sincerely,

U.S. Department of Justice
Civil Rights Division
        """,
    )
    ResponseTemplate.objects.create(
        title='CRT - Request for Agency Review',
        subject='Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }}',
        body="""
{{ addressee }},

You contacted the Department of Justice on {{ date_of_intake }}. This letter is in response to your report.

What we did:

Your report number is {{ record_locator }}.

Team members from the Civil Rights Division reviewed the information you submitted.  You indicated that you have filed a discrimination complaint with or against another Federal agency.

The Department of Justice does not serve as a reviewing authority for the decisions of other Federal agencies following their investigations of complaints about discrimination.

Therefore, we will not take further action.

What you can do:

This letter is not a determination that your report lacks merit. Your state bar association or local legal aid office may be able to help.

TO FIND...

A personal attorney

ORGANIZATION THAT MAY BE ABLE TO HELP:

American Bar Association

    Find online:
    www.findlegalhelp.org

    Contact by phone: (800) 285-2221

TO FIND...

A personal attorney for low-income individuals

ORGANIZATION THAT MAY BE ABLE TO HELP:

Legal Services Corporation (or Legal Aid Offices)

    Find online:
    www.lsc.gov/find-legal-aid

    Contact by phone: (202) 295-1500

How you helped:

While we cannot act in this specific instance, your report will help us advance civil rights. Information from reports such as yours helps us understand emerging and urgent issues. This helps inform how we protect the civil rights of all people in this country.

Thank you for taking the time to contact the Department of Justice about your concerns.

Sincerely,

U.S. Department of Justice
Civil Rights Division
        """,
    )
    ResponseTemplate.objects.create(
        title='CRT - Comments & Opinions',
        subject='Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }}',
        body="""
{{ addressee }},

You contacted the Department of Justice on {{ date_of_intake }}. Your report number is {{ record_locator }}.

We appreciate your interest and time in writing to us to express your views. Please know that the information you have provided will receive appropriate consideration.

Sincerely,

U.S. Department of Justice
Civil Rights Division
        """,
    )

def remove_templates(apps, schema_editor):
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    ResponseTemplate.objects.get(title='HCE - Referral for Housing/Lending/Public Accommodation').delete()
    ResponseTemplate.objects.get(title='SPL - Referral for PREA Issues').delete()
    ResponseTemplate.objects.get(title='CRT - Request for Agency Review').delete()
    ResponseTemplate.objects.get(title='CRT - Comments & Opinions').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0082_merge_20200702_1434'),
    ]

    operations = [
        migrations.RunPython(add_templates, remove_templates),
    ]
