# Generated by Django 2.2.13 on 2020-07-13 17:26

from django.db import migrations


def tweak_templates(apps, schema_editor):
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    # adjust template names to have a common prefix
    nonactionable = ResponseTemplate.objects.get(title='Non-Actionable')
    nonactionable.title = 'CRT - Non-Actionable'
    nonactionable.save()
    nocapacity = ResponseTemplate.objects.get(title='No capacity')
    nocapacity.title = 'CRT - No capacity'
    nocapacity.save()
    # tweak subject line format for all
    common_subject = "Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }} Section"
    templates = ResponseTemplate.objects.all()
    for template in templates:
         template.subject = common_subject
         template.save()
    # change "record number" to "report number"
    templates_with_record_number = ResponseTemplate.objects.filter(body__icontains='record number')
    for template in templates_with_record_number:
        template.body = template.body.replace('record number', 'report number')
        template.save()


def untweak_templates(apps, schema_editor):
    # don't prevent unmigrations. if we want to undo these tweaks,
    # best to unmigrate to 0074 and then migrate up to 0083.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0083_add_crt_hce_spl_form_letters'),
    ]

    operations = [
        migrations.RunPython(tweak_templates, untweak_templates),
    ]
