# Generated by Django 2.2.13 on 2020-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0086_materialize_trends_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_section',
            field=models.TextField(choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default='ADM'),
        ),
        migrations.AlterField(
            model_name='responsetemplate',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
