# Generated by Django 2.2.13 on 2020-08-17 18:07

from django.db import migrations


def tweak_subject_lines(apps, schema_editor):
    # add "the" as a prefix
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    common_subject = "Response: Your Civil Rights Division Report - {{ record_locator }} from the {{ section_name }} Section"
    templates = ResponseTemplate.objects.filter(subject__icontains='from {{ section_name }}')
    for template in templates:
         template.subject = common_subject
         template.save()


def untweak_subject_lines(apps, schema_editor):
    # don't prevent unmigrations. if we want to undo these tweaks,
    # best to unmigrate to 0074 and then migrate up to 0086.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0087_expand_form_subject_length'),
    ]

    operations = [
        migrations.RunPython(tweak_subject_lines, untweak_subject_lines)
    ]
