# Generated by Django 2.2.15 on 2020-12-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0092_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='referral_section',
            field=models.TextField(blank=True, choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], null=False),
        ),
        migrations.AddField(
            model_name='report',
            name='referred',
            field=models.BooleanField(default=False),
        ),
    ]
