# Generated by Django 2.2.17 on 2020-12-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0094_eeoc_referral_letters'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE OR REPLACE VIEW email_report_count AS
                WITH email_counts AS (
                    SELECT cts_forms_report_1.contact_email AS email,
                        count(*) AS email_count
                    FROM cts_forms_report cts_forms_report_1
                    GROUP BY cts_forms_report_1.contact_email
                    )
            SELECT cts_forms_report.id AS report_id,
                email_counts.email_count
            FROM cts_forms_report
                LEFT JOIN email_counts ON cts_forms_report.contact_email = email_counts.email;
        """)
    ]
