# Generated by Django 2.2.17 on 2020-12-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0095_create_email_report_count_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReportCount',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_report_count', serialize=False, to='cts_forms.Report')),
                ('email_count', models.IntegerField()),
            ],
            options={
                'db_table': 'email_report_count',
                'managed': False,
            },
        )
    ]
