# Generated by Django 2.2.18 on 2021-02-24 17:50

from django.db import migrations

def add_constant_writer_letters(apps, schema_editor):
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    subject = 'Response: Your Civil Rights Division Report - {{ record_locator }} from {{ section_name }} Section'
    ResponseTemplate.objects.create(
        title='CRT - Constant Writer',
        subject=subject,
        body="""
{{ addressee }},

You contacted the Department of Justice on {{ date_of_intake }}. Your report number is {{ record_locator }}. We previously received similar correspondence from you concerning this matter and we responded to that inquiry.  

There is nothing further we can add to our prior response and we sincerely regret that we cannot offer you further assistance concerning this matter.

Sincerely,

U.S. Department of Justice
Civil Rights Division
""")

    subject_es = 'Respuesta: Su informe de la División de Derechos Civiles - {{ record_locator }} de la Sección {{ es.section_name }}'
    ResponseTemplate.objects.create(
        title='CRT - Constant Writer (Spanish)',
        subject=subject_es,
        body="""
{{ es.addressee }},

Usted se comunicó con el Departamento de Justicia el {{ es.date_of_intake }}. Su número de informe es {{ record_locator }}. Recibimos anteriormente una correspondencia parecida de usted acerca de este asunto y ya respondimos a tal consulta.  

No tenemos nada más que agregar a nuestra respuesta anterior y verdaderamente lamentamos no poder ser de más ayuda con respecto a este asunto.

Atentamente,

Departamento de Justicia de los EE. UU.
División de Derechos Civiles
""")

def remove_constant_writer_letters(apps, schema_editor):
    ResponseTemplate = apps.get_model('cts_forms', 'ResponseTemplate')
    templates = ResponseTemplate.objects.filter(title__icontains='CRT - Constant Writer')
    templates.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0100_create_reportattachment'),
    ]

    operations = [
        migrations.RunPython(add_constant_writer_letters, remove_constant_writer_letters)
    ]
