# Generated by Django 2.2.18 on 2021-02-18 21:49

import cts_forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0100_create_reportattachments_20210209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattachment',
            name='file',
            field=models.FileField(upload_to='attachments', validators=[cts_forms.validators.validate_file_infection]),
        ),
    ]
