# Generated by Django 2.2.19 on 2021-03-05 17:30

import cts_forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0101_constant_writer_form_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_email',
            field=models.CharField(blank=True, max_length=225, null=True, validators=[cts_forms.validators.validate_email_address]),
        ),
    ]
