# Generated by Django 2.2.19 on 2021-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0102_international_email_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportattachment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('workplace', 'Workplace discrimination or other employment-related problem'), ('housing', 'Housing discrimination or harassment'), ('education', 'Discrimination at a school, educational program or service, or related to receiving education'), ('police', 'Mistreated by police, correctional staff, or inmates'), ('voting', 'Voting rights or ability to vote affected'), ('commercial_or_public', 'Discriminated against in a commercial location or public place'), ('something_else', 'Something else happened')], default='', max_length=100),
        ),
    ]
