# Generated by Django 2.2.19 on 2021-03-15 16:53

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0103_create_attachment_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='violation_summary_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='primary_complaint',
            field=models.CharField(choices=[('workplace', 'Workplace discrimination or other employment-related problem'), ('housing', 'Housing discrimination or harassment'), ('education', 'Discrimination at a school, educational program or service, or related to receiving education'), ('police', 'Mistreated by police, correctional staff, or inmates'), ('voting', 'Voting rights or ability to vote affected'), ('commercial_or_public', 'Discriminated against in a commercial location or public place'), ('something_else', 'Something else happened')], default='', max_length=100),
        ),
        migrations.RunSQL(sql="""
            CREATE TRIGGER violation_summary_vector_update BEFORE INSERT OR UPDATE
            ON cts_forms_report FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(violation_summary_search_vector, 'pg_catalog.english', violation_summary);

            UPDATE cts_forms_report SET primary_complaint=primary_complaint;
        """,
        reverse_sql="""
            DROP TRIGGER IF EXISTS violation_summary_vector_update ON cts_forms_report
        """),
    ]
