# Generated by Django 2.2.19 on 2021-04-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0105_add_violation_summary_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoNotEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Emails will not be sent to the address added here', max_length=254, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Do Not Email recipient',
            },
        ),
    ]
