# Generated by Django 2.2.20 on 2021-05-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0106_donotemail'),
        ('cts_forms', '0111_responsetemplate_language'),
    ]

    operations = [
    ]
