# Generated by Django 2.2.22 on 2021-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0111_responsetemplate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
