# Generated by Django 2.2.22 on 2021-06-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0112_report_language'),
        ('cts_forms', '0112_merge_20210513_1618'),
    ]

    operations = [
    ]
