# Generated by Django 2.2.24 on 2021-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0113_merge_20210604_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetemplate',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
