# Generated by Django 2.2.24 on 2021-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0123_add_indexes_new_email_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='number_contacts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
