# Generated by Django 2.2.24 on 2021-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0123_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='deploy_date',
            field=models.DateTimeField(),
        ),
    ]
