# Generated by Django 2.2.24 on 2021-11-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0124_update_auto-reply-form-letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
