# Generated by Django 2.2.24 on 2021-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0134_materialize_email_count_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
