# Generated by Django 3.2.11 on 2022-01-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0137_create_create_date_id_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='opened',
            new_name='viewed',
        ),
    ]
