# Generated by Django 3.2.11 on 2022-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0138_rename_opened_report_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_section',
            field=models.TextField(choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default='ADM'),
        ),
        migrations.AlterField(
            model_name='report',
            name='referral_section',
            field=models.TextField(blank=True, choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')]),
        ),
    ]
