# Generated by Django 3.2.11 on 2022-01-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0138_update_year_validations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='read',
            new_name='viewed',
        ),
    ]
