# Generated by Django 3.2.12 on 2022-02-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0139_add_pol_section_for_svi'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetemplate',
            name='is_html',
            field=models.BooleanField(default=False, verbose_name='HTML email'),
        ),
    ]
