# Generated by Django 3.2.12 on 2022-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0141_delete_legacy_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='referrer',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
