# Generated by Django 3.2.12 on 2022-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0142_delete_legacy_templates_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='district',
            field=models.CharField(blank=True, choices=[('1', '1 - Alabama - ND'), ('2', '2 - Alabama - MD'), ('3', '3 - Alabama - SD'), ('6', '6 - Alaska'), ('8', '8 - Arizona'), ('9', '9 - Arkansas - ED'), ('10', '10 - Arkansas - WD'), ('11', '11 - California - ND'), ('11E', '11E - California - ED'), ('12', '12 - California - SD'), ('12C', '12C - California - CD'), ('13', '13 - Colorado'), ('14', '14 - Connecticut'), ('15', '15 - Delaware'), ('16', '16 - District of Columbia'), ('17', '17 - Florida - ND'), ('17M', '17M - Florida - MD'), ('18', '18 - Florida - SD'), ('19', '19 - Georgia - ND'), ('19M', '19M - Georgia - MD'), ('20', '20 - Georgia - SD'), ('21', '21 - Hawaii'), ('22', '22 - Idaho'), ('23', '23 - Illinois - ND'), ('24', '24 - Illinois - CD'), ('25', '25 - Illinois - SD'), ('26', '26 - Indiana - ND'), ('26S', '26S - Indiana - SD'), ('27', '27 - Iowa - ND'), ('28', '28 - Iowa - SD'), ('29', '29 - Kansas'), ('30', '30 - Kentucky - ED'), ('31', '31 - Kentucky - WD'), ('32', '32 - Louisiana - ED'), ('32M', '32M - Louisiana - MD'), ('33', '33 - Louisiana - WD'), ('34', '34 - Maine'), ('35', '35 - Maryland'), ('36', '36 - Massachusetts'), ('37', '37 - Michigan - ED'), ('38', '38 - Michigan - WD'), ('39', '39 - Minnesota'), ('40', '40 - Mississippi - ND'), ('41', '41 - Mississippi - SD'), ('42', '42 - Missouri - ED'), ('43', '43 - Missouri - WD'), ('44', '44 - Montana'), ('45', '45 - Nebraska'), ('46', '46 - Nevada'), ('47', '47 - New Hampshire'), ('48', '48 - New Jersey'), ('49', '49 - New Mexico'), ('50', '50 - New York - ND'), ('51', '51 - New York - SD'), ('52', '52 - New York - ED'), ('53', '53 - New York - WD'), ('54', '54 - North Carolina - ED'), ('54M', '54M - North Carolina - MD'), ('55', '55 - North Carolina - WD'), ('56', '56 - North Dakota'), ('57', '57 - Ohio - ND'), ('58', '58 - Ohio - SD'), ('59', '59 - Oklahoma - ED'), ('59N', '59N - Oklahoma - ND'), ('60', '60 - Oklahoma - WD'), ('61', '61 - Oregon'), ('62', '62 - Pennsylvania - ED'), ('63', '63 - Pennsylvania - MD'), ('64', '64 - Pennsylvania - WD'), ('65', '65 - Puerto Rico'), ('66', '66 - Rhode Island'), ('67', '67 - South Carolina'), ('69', '69 - South Dakota'), ('70', '70 - Tennessee - ED'), ('71', '71 - Tennessee - MD'), ('72', '72 - Tennessee - WD'), ('73', '73 - Texas - ND'), ('74', '74 - Texas - SD'), ('75', '75 - Texas - ED'), ('76', '76 - Texas - WD'), ('77', '77 - Utah'), ('78', '78 - Vermont'), ('79', '79 - Virginia - ED'), ('80', '80 - Virginia - WD'), ('81', '81 - Washington - ED'), ('82', '82 - Washington - WD'), ('83', '83 - West Virginia - ND'), ('84', '84 - West Virginia - SD'), ('85', '85 - Wisconsin - ED'), ('86', '86 - Wisconsin - WD'), ('87', '87 - Wyoming'), ('90', '90 - Virgin Islands'), ('91', '91 - Guam'), ('103', '103 - Northern Mariana Islands')], max_length=7, null=True),
        ),
    ]
