# Generated by Django 2.2.10 on 2020-03-09 22:44
from django.db import migrations
from cts_forms.signals import salt


def add_public_id(apps, schema_editor):
    # add public_ids to reports that did not have them due to database failure.
    report_pks = ['10023', '10022', '10021', '10014', '10016', '1', '2300000000', '10017']
    Report = apps.get_model('cts_forms', 'Report')
    reports = Report.objects.all()
    for report_pk in report_pks:
        report = reports.filter(pk=report_pk).first()
        if report:
            salt_chars = salt()
            if not report.public_id:
                report.public_id = f'{report.pk}-{salt_chars}'
                report.save()
                print(f'Successfully write public_id to {report_pk}')
            if not report.intake_format:
                report.intake_format = 'web'
                report.save()
                print(f'Successfully write intake_format to {report_pk}')
        else:
            print(f'Report {report_pk} not found.')


class Migration(migrations.Migration):
    dependencies = [
        ('cts_forms', '0145_report_add_public_id copy'),
    ]

    operations = [
        migrations.RunPython(add_public_id)
    ]
