# Generated by Django 2.2.10 on 2020-03-09 22:44
import random

from django.db import migrations, models

from cts_forms.signals import salt


def add_public_id(apps, schema_editor):
    # add public_ids to reports that did not have them due to database failure.
    Report = apps.get_model('cts_forms', 'Report')
    incomplete_reports_pk = ['152678', '152679', '152680', '152681']
    for report_pk in incomplete_reports_pk:
        salt_chars = salt()
        report = Report.objects.filter(pk=report_pk)
        report.public_id = f'{report.pk}-{salt_chars}'
        if 'intake_format' not in report:
            report.intake_format = 'web'
        report.save()

class Migration(migrations.Migration):
    dependencies = [
        ('cts_forms', '0143_alter_report_district'),
    ]

    operations = [
        migrations.RunPython(add_public_id)
    ]
