# Generated by Django 3.2.12 on 2022-03-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0142_report_referrer'),
        ('cts_forms', '0143_alter_report_district'),
    ]

    operations = [
    ]
