# Generated by Django 2.2.10 on 2020-03-09 22:44
from django.db import migrations, models
from cts_forms.signals import salt


def add_public_id(apps, schema_editor):
    # add public_ids to reports that did not have them due to database failure.
    report_pks = ['1000000', '100']
    Report = apps.get_model('cts_forms', 'Report')
    for report_pk in report_pks:
        try: 
            report = Report.objects.get(pk=report_pk).first()
            salt_chars = salt()
            if not report.public_id:
                report.public_id = f'{report.pk}-{salt_chars}'
                print(f'Successfully write public_id to {report_pk}')
            if not report.intake_format:
                report.intake_format = 'web'
                print(f'Successfully write intake_format to {report_pk}')
            report.save()
        except report.DoesNotExist:
            print(f'{report_pk} does not exist')



class Migration(migrations.Migration):
    dependencies = [
        ('cts_forms', '0144_report_add_public_id'),
    ]

    operations = [
        migrations.RunPython(add_public_id)
    ]
