# Generated by Django 3.2.13 on 2022-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0145_materialized_form_letters_sent_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLettersSent',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assigned_section', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'form_letters_sent',
                'managed': False,
            },
        ),
    ]
