# Generated by Django 3.2.14 on 2022-07-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0148_update_disability_protected_class_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(choices=[('ADM', 'ADM'), ('APP', 'APP'), ('CRM', 'CRM'), ('DRS', 'DRS'), ('ELS', 'ELS'), ('EOS', 'EOS'), ('FCS', 'FCS'), ('HCE', 'HCE'), ('IER', 'IER'), ('POL', 'POL'), ('SPL', 'SPL'), ('VOT', 'VOT')], default='ADM', unique=True)),
                ('names', models.CharField(max_length=700)),
            ],
        ),
    ]
