# Generated by Django 3.2.14 on 2022-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0149_routingsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingStepOneContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.TextField(max_length=700)),
            ],
        ),
    ]
