# Generated by Django 3.2.15 on 2022-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0150_routingsteponecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='primary_complaint_voting',
            field=models.CharField(choices=[('voting', 'Voting rights or ability to vote affected'), ('workplace', 'Workplace discrimination or other employment-related problem'), ('housing', 'Housing discrimination or harassment'), ('education', 'Discrimination at a school, educational program or service, or related to receiving education'), ('police', 'Mistreated by police, correctional staff, or inmates'), ('commercial_or_public', 'Discriminated against in a commercial location or public place'), ('something_else', 'Something else happened')], default='', max_length=100),
        ),
    ]
