# Generated by Django 3.2.15 on 2022-09-09 13:42

import cts_forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0151_votingmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data-request', validators=[cts_forms.validators.validate_file_attachment])),
                ('filename', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
