# Generated by Django 3.2.15 on 2022-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0154_alter_reportsdata_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatWriterInfo',
            fields=[
                ('email', models.EmailField(help_text='Email associated with number of reports', max_length=254, primary_key=True, serialize=False, unique=True)),
                ('email_count', models.IntegerField()),
            ],
        ),
    ]
