# Generated by Django 3.2.15 on 2022-10-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0156_repeat_writer_materialized_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeatwriterinfo',
            options={'managed': False},
        ),
    ]
