# Generated by Django 3.2.15 on 2022-10-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0157_alter_repeatwriterinfo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repeatwriterinfo',
            table='repeat_writer_view',
        ),
    ]
