# Generated by Django 3.2.16 on 2022-12-16 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0159_remove_test_form_letters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(blank=True, help_text='The non-publicly-facing name for this campaign', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='origination_utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='origination_utm_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='origination_utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='origination_utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='origination_utm_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
