# Generated by Django 3.2.16 on 2022-12-08 19:42

from django.db import migrations
from django.db import connection


def add_repeat_summary_view(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE MATERIALIZED VIEW repeat_summary_view AS
            select UPPER(violation_summary) AS summary, count(*)
            from cts_forms_report
            group by UPPER(violation_summary);
        """)


def revert_repeat_summary_view(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            DROP MATERIALIZED VIEW repeat_summary_view;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0159_remove_test_form_letters'),
    ]

    operations = [
        migrations.RunPython(add_repeat_summary_view, revert_repeat_summary_view)
    ]
