# Generated by Django 3.2.16 on 2022-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0160_add_campaign_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='internal_name',
            field=models.CharField(help_text='The non-publicly-facing name for this campaign', max_length=100, unique=True),
        ),
    ]
