# Generated by Django 3.2.16 on 2023-01-27 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0160_gh1439_campaign_link_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetemplate',
            name='is_user_created',
            field=models.BooleanField(default=True, verbose_name='Is user created'),
        ),
        migrations.AlterField(
            model_name='report',
            name='crt_reciept_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2023)),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2023, message='Date can not be in the future.')),
        ),
    ]
