# Generated by Django 3.2.16 on 2023-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0161_auto_20230202_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetemplate',
            name='show_in_dropdown',
            field=models.BooleanField(default=True, verbose_name='Show in select template dropdown'),
        ),
    ]
