# Generated by Django 3.2.17 on 2023-02-24 19:15

from django.db import migrations, models
from django.db.migrations.operations import special


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0165_create_report_contact_email_index'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS analytics",
            reverse_sql=special.RunSQL.noop),
        migrations.CreateModel(
            name='DashboardEmbed',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('mimetype', models.CharField(default='text/html', max_length=255)),
            ],
            options={
                'db_table': 'analytics"."dashboard_embed',
            },
        ),
    ]
