# Generated by Django 3.2.17 on 2023-03-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0166_add_reporting_embeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name to show in dropdown fields.', max_length=500, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about how to use this referral information.', max_length=7000)),
                ('addressee_text', models.TextField(blank=True, help_text='What to print on printed referral forms.', max_length=7000)),
                ('addressee_emails', models.TextField(blank=True, help_text="A comma-separated list of emails to include on email referrals (for example: 'a@a.gov, b@b.gov')", max_length=7000)),
                ('show_as_referral', models.BooleanField(default=True, help_text='Whether to list this contact as a referral option.')),
            ],
        ),
    ]
