# Generated by Django 3.2.17 on 2023-03-18 15:56

import textwrap
import cts_forms.models
from django.db import migrations, models


def remove_referral_text(apps, schema_editor):
    del apps, schema_editor
    pass  # The entire column will be dropped, nothing to do here.


def add_referral_text(apps, schema_editor):
    del schema_editor  # Unused

    ReferralContact = apps.get_model('cts_forms', 'ReferralContact')
    variable_texts = {
        'va': {
            'en': textwrap.dedent("""
U.S. Department of Veterans Affairs
(202) 501-2800
                                  """).strip(),
            'es': textwrap.dedent("""
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
                                  """).strip(),
            'vi': textwrap.dedent("""
                                  """).strip(),
            'ko': textwrap.dedent("""
                                  """).strip(),
            'tl': textwrap.dedent("""
                                  """).strip(),
        },

        'ssa-ogc': {
            'en': textwrap.dedent("""
Social Security Administration
1-800-772-1213
1-800-325-0778 (TTY)
                                  """).strip(),
            'es': textwrap.dedent("""
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
                                  """).strip(),
            'vi': textwrap.dedent("""
                                  """).strip(),
            'ko': textwrap.dedent("""
                                  """).strip(),
            'tl': textwrap.dedent("""
                                  """).strip(),
        },

        'ssa-opi': {
            'en': textwrap.dedent("""
Social Security Administration
1-800-772-1213
1-800-325-0778 (TTY)
                                  """).strip(),
            'es': textwrap.dedent("""
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
                                  """).strip(),
            'vi': textwrap.dedent("""
                                  """).strip(),
            'ko': textwrap.dedent("""
                                  """).strip(),
            'tl': textwrap.dedent("""
                                  """).strip(),
        },

        'dot-ocr': {
            'en': textwrap.dedent("""
U.S. Department of Transportation: Departmental Office of Civil Rights
(202) 366-4648 (voice) and (202) 366-8538 (TTY)
                                  """).strip(),
            'es': textwrap.dedent("""
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
                                  """).strip(),
            'vi': textwrap.dedent("""
                                  """).strip(),
            'ko': textwrap.dedent("""
                                  """).strip(),
            'tl': textwrap.dedent("""
                                  """).strip(),
        },

        'dot-fta': {
            'en': textwrap.dedent("""
U.S. Department of Transportation: Federal Transit Administration
(888) 446-4511.
                                  """).strip(),
            'es': textwrap.dedent("""
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
                                  """).strip(),
            'vi': textwrap.dedent("""
                                  """).strip(),
            'ko': textwrap.dedent("""
                                  """).strip(),
            'tl': textwrap.dedent("""
                                  """).strip(),
        },

        'dot-acp': {
            'en': textwrap.dedent("""
Department of Transportation, Aviation Consumer Protection Division
(202) 366-4648 (voice); (202) 366-8538 (TTY)
                                  """).strip(),
            'es': textwrap.dedent("""
Department of Transportation, Aviation Consumer Protection Division
(202) 366-4648 (voz); (202) 366-8538 (TTY)
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
交通部，航空消費者保護司 (Department of Transportation, Aviation Consumer Protection Division)
(202) 366-4648 (有聲); (202) 366-8538 (聽障人士專用)
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
交通部，航空消费者保护司 (Department of Transportation, Aviation Consumer Protection Division)
(202) 366-4648 (有声); (202) 366-8538 (听障人士专线)
                                  """).strip(),
            'vi': textwrap.dedent("""
Bộ Giao Thông Vận Tải, Bộ Phận Bảo Vệ Khách Hàng Hàng Không (Department of Transportation, Aviation Consumer Protection Division)
(202) 366-4648 (dùng tiếng nói); (202) 366-8538 (TTY)
                                  """).strip(),
            'ko': textwrap.dedent("""
교통부, 항공 소비자 보호 부서 (Department of Transportation, Aviation Consumer Protection Division)
(202) 366-4648 (음성); (202) 366-8538 (TTY)
                                  """).strip(),
            'tl': textwrap.dedent("""
Kagawaran ng Transportasyon, Dibisyon para sa Proteksyon ng Mamimili sa Abyasyon (Department of Transportation, Aviation Consumer Protection Division)
(202) 366-4648 (boses); (202) 366-8538 (gamit makinilya)
                                  """).strip(),
        },

        'eeoc': {
            'en': textwrap.dedent("""
U.S. Equal Employment Opportunity Commission
1-800-669-4000
1-800-669-6820 (TTY for Deaf/Hard of Hearing callers only)
1-844-234-5122 (ASL Video Phone for Deaf/Hard of Hearing callers only)
https://www.eeoc.gov/
                                  """).strip(),
            'es': textwrap.dedent("""
U.S. Equal Employment Opportunity Commission
1-800-669-4000
1-800-669-6820 (TTY exclusivamente para interlocutores sordos/con discapacidades auditivas)
1-844-234-5122 (Videoteléfono de ASL exclusivamente para interlocutores sordos/con discapacidades auditivas)
https://www.eeoc.gov/
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
美國平等就業機會委員會 (U.S. Equal Employment Opportunity Commission)
1-800-669-4000
1-800-669-6820 (耳聾或聽力障礙人士打電話專用電傳打字機)
1-844-234-5122 (耳聾或聽力障礙人士打電話專用美國手語視頻電話)
https://www.eeoc.gov/
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
美国平等就业机会委员会 (U.S. Equal Employment Opportunity Commission)
1-800-669-4000
1-800-669-6820 (文字电话仅适用于失聪/听障来电者)
1-844-234-5122 (美国手语视频电话仅适用失聪/听障来电者)
https://www.eeoc.gov/
                                  """).strip(),
            'vi': textwrap.dedent("""
Ủy Ban Cơ Hội Việc Làm Bình Đẳng của Hoa Kỳ (U.S. Equal Employment Opportunity Commission)
1-800-669-4000
1-800-669-6820 (Chế độ TTY chỉ dành riêng cho người gọi Khiếm Thính/Lãng Tai)
1-844-234-5122 (Hệ Thống Điện Thoại Video ASL chỉ dành riêng cho người gọi Khiếm Thính/Lãng Tai)
https://www.eeoc.gov/
                                  """).strip(),
            'ko': textwrap.dedent("""
미국 평등 고용 기회 위원회 (U.S. Equal Employment Opportunity Commission)
1-800-669-4000
1-800-669-6820 (청각장애인 전용 TTY (문자 전화))
1-844-234-5122 (청각장애인 전용 ASL (미국 수화) 영상전화)
https://www.eeoc.gov/
                                  """).strip(),
            'tl': textwrap.dedent("""
Komisyon para sa Pantay na Oportunidad sa Trabaho ng Estados Unidos (U.S. Equal Employment Opportunity Commission)
1-800-669-4000
1-800-669-6820 (TTY para sa Bingi/Para lamang sa mga tumatawag na Mahina ang Pandinig)
1-844-234-5122 (ASL Bideyong Telepono para sa Bingi/ Para lamang sa mga tumatawag na Mahina ang Pandinig)
https://www.eeoc.gov/
                                  """).strip(),
        },

        'hhs': {
            'en': textwrap.dedent("""
Department of Health and Human Services
1-800-368-1019
                                  """).strip(),
            'es': textwrap.dedent("""
Department of Health and Human Services
1-800-368-1019
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
衛生和公衆服務部(Department of Health and Human Services)
1-800-368-1019
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
卫生和公众服务部(Department of Health and Human Services)
1-800-368-1019
                                  """).strip(),
            'vi': textwrap.dedent("""
Bộ Y Tế và Dịch Vụ Nhân Sinh (Department of Health and Human Services)
1-800-368-1019
                                  """).strip(),
            'ko': textwrap.dedent("""
보건 복지부 (Department of Health and Human Services)
1-800-368-1019
                                  """).strip(),
            'tl': textwrap.dedent("""
Kagawaran ng Kalusugan at mga Serbisyong Pantao (Department of Health and Human Services)
1-800-368-1019
                                  """).strip(),
        },

        'doe': {
            'en': textwrap.dedent("""
U.S. Department of Education, Office for Civil Rights
(800) 421-3481; (202) 453-6012 (fax); (800) 877-8339 (TDD)
OCR@ed.gov
https://www2.ed.gov/about/offices/list/ocr/index.html
                                  """).strip(),
            'es': textwrap.dedent("""
U.S. Department of Education, Office for Civil Rights
(800) 421-3481; (202) 453-6012 (fax); (800) 877-8339 (TDD)
OCR@ed.gov
                                  """).strip(),
            'zh-hant': textwrap.dedent("""
美國教育部，民權辦公室 (U.S. Department of Education, Office for Civil Rights)
(800) 421-3481; (202) 453-6012 (傳真); (800) 877-8339 (聽障人士專用)
OCR@ed.gov
                                  """).strip(),
            'zh-hans': textwrap.dedent("""
美国教育部，民权办公室 (U.S. Department of Education, Office for Civil Rights)
(800) 421-3481; (202) 453-6012 (传真); (800) 877-8339 (听障人士专线)
OCR@ed.gov
                                  """).strip(),
            'vi': textwrap.dedent("""
Bộ Giáo Dục Hoa Kỳ, Văn Phòng Phụ Trách Dân Quyền (U.S. Department of Education, Office for Civil Rights)
(800) 421-3481; (202) 453-6012 (fax); (800) 877-8339 (TDD)
OCR@ed.gov
                                  """).strip(),
            'ko': textwrap.dedent("""
미국 교육부, 민권사무소 (U.S. Department of Education, Office for Civil Rights)
(800) 421-3481; (202) 453-6012 (팩스); (800) 877-8339 (TDD)
OCR@ed.gov
                                  """).strip(),
            'tl': textwrap.dedent("""
Kagawaran ng Edukasyon ng Estados Unidos, Tanggapan para sa mga Karapatang Sibil (U.S. Department of Education, Office for Civil Rights)
(800) 421-3481; (202) 453-6012 (fax); (800) 877-8339 (Telekomunikasyon para sa mga Bingi)
OCR@ed.gov
                                  """).strip(),
        },
    }

    for machine_name, translations in variable_texts.items():
        contact = ReferralContact.objects.get(machine_name=machine_name)
        contact.variable_text = translations
        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0167_populate_referral_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcontact',
            name='variable_text',
            field=models.JSONField(default=cts_forms.models.make_translated_text, help_text='Text to display when using the {{ referral_text }} variable in Response Templates.', validators=[cts_forms.models.validate_translated_text]),
        ),
        migrations.RunPython(add_referral_text, remove_referral_text),
    ]
