# Generated by Django 3.2.17 on 2023-03-18 15:56

import cts_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0167_populate_referral_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcontact',
            name='variable_text',
            field=models.JSONField(default=cts_forms.models.make_translated_text, help_text='Text to display when using the {{ referral_text }} variable in Response Templates.', validators=[cts_forms.models.validate_translated_text]),
        ),
    ]
