# Generated by Django 3.2.17 on 2023-03-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0167_add_referral_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetemplate',
            name='referral_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_templates', to='cts_forms.referralcontact'),
        ),
    ]
