# Generated by Django 3.2.17 on 2023-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0169_primary_statute'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
