# Generated by Django 3.2.17 on 2023-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0170_campaign_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='section',
            field=models.TextField(choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], null=True),
        ),
    ]
