# Generated by Django 3.2.17 on 2023-05-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0172_report_dj_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardembed',
            options={},
        ),
    ]
