# Generated by Django 3.2.17 on 2023-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0173_alter_dashboardembed_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submission_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
