# Generated by Django 3.2.17 on 2023-05-23 20:28

import cts_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0173_alter_dashboardembed_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='The order in which to show the message, lower numbers first. If two messages have the same order number, they might change positions.')),
                ('show', models.BooleanField(default=False, help_text='Whether to show the message on the public landing page.')),
                ('kind', models.CharField(choices=[('notice', 'notice'), ('alert', 'alert'), ('emergency', 'emergency')], default='warning', max_length=10)),
                ('markdown_content', models.JSONField(default=cts_forms.models.make_translated_text, help_text='Markdown to render and display in the banner.', validators=[cts_forms.models.validate_translated_text])),
            ],
        ),
    ]
