# Generated by Django 3.2.17 on 2023-06-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0174_bannermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='origination_utm_campaign',
            field=models.ForeignKey(blank=True, help_text='The internal name of the outreach effort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cts_forms.campaign'),
        ),
        migrations.AlterField(
            model_name='report',
            name='origination_utm_content',
            field=models.CharField(blank=True, help_text='The specific link or section of material (such as a banner or text link) that was followed to make the report', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='origination_utm_medium',
            field=models.CharField(blank=True, help_text='What type of content or link was used, such as email, website, physical mail, etc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='origination_utm_source',
            field=models.CharField(blank=True, help_text='Identifies which site sent the traffic, e.g. justice.gov/crt or ada.gov', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='origination_utm_term',
            field=models.CharField(blank=True, help_text='Any search terms used in discovering the outreach effort', max_length=100, null=True),
        ),
    ]
