# Generated by Django 3.2.17 on 2023-06-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0175_update_outreach_tooltips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='origination_utm_campaign',
            field=models.ForeignKey(blank=True, help_text='The internal name of the outreach effort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cts_forms.campaign', verbose_name='Outreach Name'),
        ),
    ]
