# Generated by Django 4.2.3 on 2023-08-29 22:33

import datetime

from django.contrib.auth import get_user_model
from django.db import migrations, models


def add_system_user(apps, schema_editor):
    del apps, schema_editor  # Unused
    get_user_model().objects.create(
        username='system.user',
        first_name='System',
        last_name='User',
        email='system@localhost',
        is_staff=False,
        is_superuser=False,
        is_active=False,
        last_login=datetime.datetime.now(),
    )


def remove_system_user(apps, schema_editor):
    del apps, schema_editor  # Unused
    get_user_model().objects.filter(username='system.user').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0176_alter_report_origination_utm_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the search as it will appear in lists and dropdowns.', max_length=255)),
                ('query', models.TextField(default='status=new&status=open&no_status=false&grouping=default', help_text='The encoded search represented as a URL querystring for the /form/view page.')),
                ('auto_close', models.BooleanField(default=False, help_text='Whether to automatically close incoming reports that match this search. Only applies to new submissions.')),
                ('auto_close_reason', models.CharField(blank=True, help_text="The reason to add to the report summary when auto-closing. Will be filled in the following blank: 'Report automatically closed on submission because ____'", max_length=255, null=True)),
            ],
        ),
        migrations.RunPython(add_system_user, remove_system_user),
    ]
