# Generated by Django 4.2.3 on 2023-09-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0176_alter_report_origination_utm_campaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardEmbed',
        ),
    ]
