# Generated by Django 4.2.3 on 2023-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0177_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='override_section_assignment',
            field=models.BooleanField(default=False, help_text='Whether to override the section assignment for all reports with this campaign'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='override_section_assignment_with',
            field=models.TextField(blank=True, choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], help_text="If set, this will override the section assignment for all reports with this campaign. This can be used to 'tweak' the routing logic based on Personal Description, etc.", null=True),
        ),
    ]
