# Generated by Django 4.2.3 on 2023-09-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0178_savedsearch_override_section_assignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardEmbed',
        ),
    ]
