# Generated by Django 4.2.3 on 2023-09-18 18:13

from django.db import migrations, models


def add_initial_schedules(apps, schema_editor):
    del schema_editor  # Unused

    RetentionSchedule = apps.get_model('cts_forms', 'RetentionSchedule')
    RetentionSchedule.objects.create(
        name='1 Year',
        order=0,
        description='',
        tooltip='Public Correspondence – No Response',
        retention_years=1,
        da_number='DAA-0060-2014-0004-0001',
    )
    RetentionSchedule.objects.create(
        name='3 Year',
        order=1,
        description='',
        tooltip='Public Correspondence – Response Required',
        retention_years=3,
        da_number='DAA-0060-2014-0004-0002',
    )
    RetentionSchedule.objects.create(
        name='10 Year',
        order=2,
        description='',
        tooltip='General DJ Number Files – GNT',
        retention_years=10,
        da_number='DAA-0060-2017-0022-0002',
    )
    RetentionSchedule.objects.create(
        name='Permanent',
        order=3,
        description='',
        tooltip='General DJ Number Files – GNP',
        retention_years=0,
        da_number='DAA-0060-2017-0022-0001',
    )


def remove_initial_schedules(apps, schema_editor):
    del schema_editor  # Unused

    RetentionSchedule = apps.get_model('cts_forms', 'RetentionSchedule')
    RetentionSchedule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0179_delete_dashboardembed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the schedule that will be shown to intake specialists in dropdowns.', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='The order in which to show the schedules, lower numbers first. If two schedules have the same order number, they might change positions.')),
                ('description', models.TextField(blank=True, help_text='Internal notes, shown only here, about this schedule.', max_length=7000)),
                ('tooltip', models.CharField(blank=True, help_text='The text to show in the tooltip for this schedule.', max_length=255)),
                ('retention_years', models.IntegerField(help_text='The number of years to retain reports with this schedule (following their closure). Set to 0 for permanent retention.')),
                ('da_number', models.CharField(help_text='The disposition authority number for this schedule (assigned by NARA).', max_length=255)),
                ('is_retired', models.BooleanField(default=False, help_text='Whether this schedule is no longer active (show as a retired / expired schedule)')),
            ],
        ),
        migrations.RunPython(add_initial_schedules, remove_initial_schedules),
    ]
