# Generated by Django 4.2.3 on 2023-09-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0180_retentionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='litigation_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='retention_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cts_forms.retentionschedule'),
        ),
    ]
