# Generated by Django 4.2.3 on 2023-10-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cts_forms', '0184_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetemplate',
            name='is_notification',
            field=models.BooleanField(default=False, verbose_name='Only for use by notification systems'),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.BooleanField(default=False, verbose_name='Assigned to a report')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
