# Generated by Django 4.2.3 on 2023-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0185_responsetemplate_is_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='The Date this report\'s status was most recently set to "Closed" plus the length of the Retention Schedule', null=True),
        ),
    ]
