# Generated by Django 4.2.3 on 2023-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0185_responsetemplate_is_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag that will be shown throughout the app.', max_length=255)),
                ('section', models.TextField(blank=True, choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default=None, help_text='The section to which this tag applies. If set, this tag will only be available to reports in this section.', null=True)),
                ('tooltip', models.CharField(blank=True, help_text='The text to show in the tooltip for this tag.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Long-form notes about this tag, not shown on most pages.', max_length=7000)),
                ('show_in_lists', models.BooleanField(default=False, help_text='Whether to show this tag in the list page and dropdowns')),
            ],
            options={
                'permissions': (('assign_tag', 'Can assign tags to reports'),),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cts_forms.tag'),
        ),
    ]
