# Generated by Django 4.2.3 on 2023-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0186_report_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='eligible_date',
            field=models.DateTimeField(blank=True, help_text='The Date this report is eligible for disposal, 30 days before the expiration date', null=True),
        ),
    ]
