# Generated by Django 4.2.3 on 2023-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0186_tag_report_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('order', models.IntegerField(default=0, help_text='The order in which to show the name, lower numbers first. If two names have the same order number, they might change positions.')),
            ],
        ),
    ]
