# Generated by Django 4.2.3 on 2023-12-14 18:33

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0187_applicationcontact'),
    ]

    operations = [
        CreateExtension('fuzzystrmatch'),
        TrigramExtension(),
    ]
