# Generated by Django 4.2.3 on 2023-12-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0188_add_fuzzy_extensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routingsection',
            options={'verbose_name': 'Section POC', 'verbose_name_plural': 'Section POCs'},
        ),
        migrations.AddField(
            model_name='routingsection',
            name='retention_section_pocs',
            field=models.CharField(default='', max_length=700, verbose_name='Retention Section POCs'),
        ),
        migrations.AlterField(
            model_name='routingsection',
            name='names',
            field=models.CharField(default='', max_length=700, verbose_name='Routing Section POCs'),
        ),
    ]
