# Generated by Django 4.2.3 on 2023-12-20 16:47

from django.db import migrations
from django.db.models import Q


def backfill_ten_year_retention(apps, schema_editor):
    del schema_editor  # unused
    RetentionSchedule = apps.get_model('cts_forms', 'RetentionSchedule')
    Report = apps.get_model('cts_forms', 'Report')
    ten_year = RetentionSchedule.objects.get(retention_years=10)

    Report.objects.filter(
        Q(dj_number__isnull=True) | Q(dj_number='') | Q(dj_number='--'),
        retention_schedule__isnull=True,
        status='closed',
    ).exclude(
        litigation_hold=True,
    ).update(retention_schedule=ten_year)


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0189_alter_routingsection_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_ten_year_retention),
    ]
