# Generated by Django 4.2.3 on 2024-01-04 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0189_alter_routingsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='crt_reciept_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2024)),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2024, message='Date can not be in the future.')),
        ),
    ]
