# Generated by Django 4.2.3 on 2024-02-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0193_report_disposed_reportdispositionbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_searches',
            field=models.ForeignKey(blank=True, help_text='The user who created this saved search.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cts_forms.savedsearch'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='section',
            field=models.TextField(blank=True, choices=[('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default=None, help_text='The section to which this saved search applies.', null=True),
        ),
    ]
