# Generated by Django 4.2.3 on 2024-02-28 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cts_forms', '0194_profile_saved_searches_savedsearch_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_searches',
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='shared',
            field=models.BooleanField(default=False, help_text='Whether the search is viewable and editable by the rest of the portal users.'),
        ),
    ]
