# Generated by Django 4.2.3 on 2024-02-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0194_savedsearch_section_savedsearch_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedsearch',
            old_name='user',
            new_name='created_by',
        ),
    ]
