# Generated by Django 4.2.3 on 2024-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0194_savedsearch_section_savedsearch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='shared',
            field=models.BooleanField(default=False, help_text='Whether the search is viewable and editable by the rest of the portal users.'),
        ),
    ]
