# Generated by Django 4.2.3 on 2024-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0195_remove_profile_saved_searches_savedsearch_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='query',
            field=models.TextField(default='', help_text='The encoded search represented as a URL querystring for the /form/view page.'),
        ),
    ]
