# Generated by Django 4.2.3 on 2024-03-01 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0195_remove_profile_saved_searches_savedsearch_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 12, 37, 32, 483298)),
        ),
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='proposed_disposal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
