# Generated by Django 4.2.3 on 2024-03-12 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cts_forms', '0196_reportdispositionbatch_create_date_and_more_squashed_0197_report_batched_for_disposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='first_reviewer',
            field=models.ForeignKey(blank=True, help_text='First records team reviewer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_disposed_report_batch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about batch.', max_length=7000),
        ),
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='second_reviewer',
            field=models.ForeignKey(blank=True, help_text='Second records team reviewer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_reviewed_disposed_report_batch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='status',
            field=models.TextField(choices=[('ready', 'Ready'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='ready'),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 11, 27, 23, 938946)),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='disposed_by',
            field=models.ForeignKey(help_text='Intake specialist who created batch.', on_delete=django.db.models.deletion.PROTECT, related_name='disposed_report_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
