# Generated by Django 4.2.3 on 2024-03-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cts_forms', '0199_reportdispositionbatch_first_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='disposed_by',
            field=models.ForeignKey(blank=True, help_text='Intake specialist who created batch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposed_report_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
