# Generated by Django 4.2.3 on 2024-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0200_alter_reportdispositionbatch_disposed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='query',
            field=models.TextField(default='', help_text='The encoded search represented as a URL querystring for the /form/view page.'),
        ),
    ]
