# Generated by Django 4.2.3 on 2024-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0202_alter_reportdispositionbatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdispositionbatch',
            name='second_review_notes',
            field=models.TextField(blank=True, help_text='Internal notes about batch from the second reviewer.', max_length=7000, null=True),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about batch from the first reviewer.', max_length=7000, null=True),
        ),
    ]
