# Generated by Django 4.2.10 on 2024-04-09 16:26

from django.db import migrations, models
import django.db.models.deletion


def _backfill_shortened_urls(apps, schema_editor):
    SavedSearch = apps.get_model('cts_forms', 'SavedSearch')

    for search in SavedSearch.objects.all():
        search.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_add_short_url'),
        ('cts_forms', '0203_reportdispositionbatch_second_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='shortened_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.shortenedurl'),
        ),
        migrations.RunPython(
            code=_backfill_shortened_urls,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
