# Generated by Django 4.2.11 on 2024-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0204_savedsearch_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='inside_correctional_facility',
            field=models.CharField(blank=True, choices=[('inside', 'Yes'), ('outside', 'No')], default=None, max_length=255, null=True),
        ),
    ]
