# Generated by Django 4.2.11 on 2024-05-10 20:05

from django.db import migrations, models


def _migrate_up(apps, schema_editor):

    NotificationPreference = apps.get_model('cts_forms', 'NotificationPreference')

    for preference in NotificationPreference.objects.all():
        preference.assigned_to = 'individual' if preference.assigned_to_old else 'none'
        preference.save()


def _migrate_down(apps, schema_editor):

    NotificationPreference = apps.get_model('cts_forms', 'NotificationPreference')

    for preference in NotificationPreference.objects.all():
        preference.assigned_to_old = preference.assigned_to == 'individual'
        preference.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0205_alter_report_inside_correctional_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='assigned_to',
            new_name='assigned_to_old',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='assigned_to',
            field=models.CharField(choices=[('none', 'None'), ('individual', 'Individual'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='none', verbose_name='Assigned to a report'),
        ),
        migrations.RunPython(_migrate_up, _migrate_down),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='assigned_to_old',
        )
    ]
