# Generated by Django 4.2.3 on 2024-05-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0205_alter_report_inside_correctional_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdisposition',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
