# Generated by Django 4.2.3 on 2024-06-04 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cts_forms', '0207_reportdisposition_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_searches',
            field=models.JSONField(blank=True, default=dict, help_text='Contains the notification cadence for each saved search. The key is the saved search ID, and the value is the cadence.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_searches_last_checked',
            field=models.JSONField(blank=True, default=dict, help_text='The last time each search was checked for new reports.'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_disposition_status',
            field=models.TextField(blank=True, choices=[('rejected', 'Rejected'), ('approved', 'Approved')], null=True),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='status',
            field=models.TextField(choices=[('ready', 'Ready'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='ready'),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.JSONField()),
                ('frequency', models.CharField(choices=[('none', 'None'), ('individual', 'Individual'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField()),
                ('was_sent', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
