# Generated by Django 4.2.3 on 2024-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0207_reportdisposition_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.TextField(choices=[('new', 'New'), ('open', 'Open'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new'),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='status',
            field=models.TextField(choices=[('ready', 'Ready'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='ready'),
        ),
    ]
