# Generated by Django 4.2.3 on 2024-05-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0207_reportdisposition_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_disposition_status',
            field=models.TextField(blank=True, choices=[('rejected', 'Rejected'), ('approved', 'Approved')], null=True),
        ),
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='status',
            field=models.TextField(choices=[('ready', 'Ready'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='ready'),
        ),
    ]
