# Generated by Django 4.2.3 on 2024-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0207_reportdisposition_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejected_for_disposal',
            field=models.BooleanField(default=False),
        ),
    ]
