# Generated by Django 4.2.11 on 2024-05-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0207_schedulednotification'),
        ('cts_forms', '0208_report_report_disposition_status_and_more'),
    ]

    operations = [
    ]
