# Generated by Django 4.2.11 on 2024-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0209_merge_20240524_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_searches',
            field=models.JSONField(blank=True, default=dict, help_text='Contains the notification cadence for each saved search. The key is the saved search ID, and the value is the cadence.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_searches_last_checked',
            field=models.JSONField(blank=True, default=dict, help_text='The last time each search was checked for new reports.'),
        ),
    ]
