# Generated by Django 4.2.11 on 2024-06-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0210_notificationpreference_saved_searches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdispositionbatch',
            name='status',
            field=models.TextField(choices=[('ready', 'Ready'), ('in_review', 'In Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='ready'),
        ),
    ]
