# Generated by Django 4.2.11 on 2024-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0213_grouppreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contact_inmate_number',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
