# Generated by Django 4.2.11 on 2024-08-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0216_resourcecontact_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.TextField(blank=True, help_text='Address of resource website.', null=True),
        ),
    ]
