# Generated by Django 4.2.11 on 2024-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0217_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='background',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='need_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='outreach_efforts',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='soi_opportunities',
            field=models.BooleanField(default=False),
        ),
    ]
