# Generated by Django 4.2.11 on 2024-10-04 13:42

from django.db import migrations
from cts_forms.models import AddConfigurableContentMigration


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0219_configurablecontent'),
    ]

    operations = [
        AddConfigurableContentMigration('vot-form-links', content="""
<ul class="usa-list--unstyled margin-bottom-2">
    <li><a href="#link-here" class="usa-link">text-here</a></li>
</ul>
"""),
    ]
