# Generated by Django 4.2.11 on 2024-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0221_add_vot_state_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppreferences',
            name='saved_searches_threshold',
            field=models.JSONField(blank=True, default=dict, help_text='The threshold of results to trigger a notification for each search defaulting to 0 if none is set.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_searches_count',
            field=models.JSONField(blank=True, default=dict, help_text='The total result counts of each search since the last threshold notification was sent.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_searches_threshold',
            field=models.JSONField(blank=True, default=dict, help_text='The threshold of results to trigger a notification for each search defaulting to 0 if none is set.'),
        ),
    ]
