# Generated by Django 4.2.11 on 2024-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0222_grouppreferences_saved_searches_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
