# Generated by Django 4.2.11 on 2024-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0223_report_location_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
