# Generated by Django 4.2.16 on 2024-12-13 15:59

from django.db import migrations, models
import django.db.models.deletion


def remove_eeoc_offices(apps, schema_editor):
    del schema_editor  # Unused

    EeocOffice = apps.get_model('cts_forms', 'EeocOffice')
    EeocOffice.objects.all().delete()


def add_eeoc_offices(apps, schema_editor):
    del schema_editor  # Unused

    EeocOffice = apps.get_model('cts_forms', 'EeocOffice')

    EeocOffice.objects.create(
        name='EEOC Headquarters',
        address_line_1='U.S. Equal Employment Opportunity Commission',
        address_line_2='131 M Street, N.E.',
        address_city='Washington',
        address_state='DC',
        address_zip='20507',
        order=0,
        show=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0225_report_contact_2_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EeocOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the EEOC office that will be shown to intake specialists in dropdowns.', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='The order in which to show the offices, lower numbers first. If two offices have the same order number, they might change positions.')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands'), ('AE', 'Armed Forces Africa'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Canada'), ('AE', 'Armed Forces Europe'), ('AE', 'Armed Forces Middle East'), ('AP', 'Armed Forces Pacific')], max_length=100)),
                ('address_zip', models.CharField(max_length=10)),
                ('show', models.BooleanField(default=True, help_text='Whether to show this office in the list of EEOC offices.')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='eeoc_charge_number',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='eeoc_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cts_forms.eeocoffice'),
        ),
        migrations.RunPython(add_eeoc_offices, remove_eeoc_offices),
    ]
