# Generated by Django 4.2.16 on 2025-01-07 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0226_eeocoffice_report_eeoc_charge_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='crt_reciept_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2025)),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2025, message='Date can not be in the future.')),
        ),
    ]
