# Generated by Django 4.2.16 on 2025-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0227_alter_report_crt_reciept_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='working_group',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
