# Generated by Django 4.2.16 on 2025-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0227_alter_report_crt_reciept_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eeocoffice',
            name='url',
            field=models.CharField(default='', help_text='A link to the page that contains the contact information associated with this EEOC Office. Ex: https://www.eeoc.gov/field-office/atlanta/location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='working_group',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
