# Generated by Django 4.2.16 on 2025-01-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0228_eeocoffice_url'),
        ('cts_forms', '0228_report_working_group'),
    ]

    operations = [
    ]
