# Generated by Django 4.2.16 on 2025-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0228_eeocoffice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='working_group',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
