# Generated by Django 4.2.16 on 2025-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0230_alter_hatecrimesandtrafficking_hatecrimes_trafficking_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShutdownMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.BooleanField(default=False)),
            ],
        ),
    ]
