# Generated by Django 4.2.20 on 2025-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0233_reported_reason_data_remediation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_portal_access',
            field=models.BooleanField(default=False),
        ),
    ]
