# Generated by Django 4.2.20 on 2025-05-22 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0234_profile_has_portal_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_phone',
            field=models.CharField(blank=True, max_length=225, null=True, validators=[django.core.validators.RegexValidator('^(?=^\\D*(\\d\\D*){7,15}$)(?=^(?:(?![a-zA-Z]).)*$).*$', message='If you submit a phone number, please make sure to include between 7 and 15 digits. The characters "+", ")", "(", "-", and "." are allowed. Please include country code if entering an international phone number.')]),
        ),
    ]
