# Generated by Django 4.2.21 on 2025-06-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0235_report_location_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mediation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='mediation_number',
            field=models.CharField(blank=True, help_text='The mediation number assigned to this report, if applicable.', max_length=20, null=True),
        ),
    ]
