# Generated by Django 4.2.21 on 2025-06-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0235_report_location_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediationNumberTracker',
            fields=[
                ('state', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('next_number', models.IntegerField(default=3000)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='mediation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='mediation_number',
            field=models.CharField(blank=True, help_text='The mediation number assigned to this report, if applicable.', max_length=20, null=True),
        ),
    ]
