# Generated by Django 5.2.12 on 2026-07-07 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0237_add_gun_ownership_protected_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='section',
            field=models.TextField(choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.TextField(blank=True, choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='protectedclass',
            name='protected_class',
            field=models.CharField(blank=True, choices=[('age', 'Age'), ('disability', 'Disability (including temporary or recovered and including HIV and drug addiction)'), ('family_status', 'Family, marital, or parental status'), ('gender', 'Gender identity (including gender stereotypes)'), ('genetic', 'Genetic information (including family medical history)'), ('gun_ownership', 'Gun Ownership'), ('immigration', 'Immigration/citizenship status (choosing this will not share your status)'), ('language', 'Language'), ('national_origin', 'National origin (including ancestry and ethnicity)'), ('pregnancy', 'Pregnancy'), ('race/color', 'Race/color'), ('religion', 'Religion'), ('sex', 'Sex'), ('orientation', 'Sexual orientation'), ('none', 'None of these apply to me'), ('other', 'Other reason')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='protectedclass',
            name='value',
            field=models.CharField(blank=True, choices=[('age', 'Age'), ('disability', 'Disability (including temporary or recovered and including HIV and drug addiction)'), ('family_status', 'Family, marital, or parental status'), ('gender', 'Gender identity (including gender stereotypes)'), ('genetic', 'Genetic information (including family medical history)'), ('gun_ownership', 'Gun Ownership'), ('immigration', 'Immigration/citizenship status (choosing this will not share your status)'), ('language', 'Language'), ('national_origin', 'National origin (including ancestry and ethnicity)'), ('pregnancy', 'Pregnancy'), ('race/color', 'Race/color'), ('religion', 'Religion'), ('sex', 'Sex'), ('orientation', 'Sexual orientation'), ('none', 'None of these apply to me'), ('other', 'Other reason')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_section',
            field=models.TextField(choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default='ADM'),
        ),
        migrations.AlterField(
            model_name='report',
            name='crt_reciept_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2026)),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_incident_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(2026, message='Date can not be in the future.')),
        ),
        migrations.AlterField(
            model_name='report',
            name='referral_section',
            field=models.TextField(blank=True, choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='section',
            field=models.TextField(blank=True, choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default=None, help_text='The section to which this resource applies.', null=True),
        ),
        migrations.AlterField(
            model_name='routingsection',
            name='section',
            field=models.TextField(choices=[('2AS', '2AS'), ('ADM', 'ADM'), ('APP', 'APP'), ('CRM', 'CRM'), ('DRS', 'DRS'), ('ELS', 'ELS'), ('EOS', 'EOS'), ('FCS', 'FCS'), ('HCE', 'HCE'), ('IER', 'IER'), ('POL', 'POL'), ('SPL', 'SPL'), ('VOT', 'VOT')], default='ADM', unique=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='override_section_assignment_with',
            field=models.TextField(blank=True, choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], help_text="If set, this will override the section assignment for all reports with this campaign. This can be used to 'tweak' the routing logic based on Personal Description, etc.", null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='section',
            field=models.TextField(blank=True, choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default=None, help_text='The section to which this saved search applies.', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='section',
            field=models.TextField(blank=True, choices=[('2AS', 'Second Amendment Rights'), ('ADM', 'Administrative'), ('APP', 'Appellate'), ('CRM', 'Criminal'), ('DRS', 'Disability Rights'), ('ELS', 'Employment Litigation'), ('EOS', 'Educational Opportunities'), ('FCS', 'Federal Coordination and Compliance'), ('HCE', 'Housing and Civil Enforcement'), ('IER', 'Immigrant and Employee Rights'), ('POL', 'Policy'), ('SPL', 'Special Litigation'), ('VOT', 'Voting')], default=None, help_text='The section to which this tag applies. If set, this tag will only be available to reports in this section.', null=True),
        ),
    ]
