# Generated by Django 2.2.13 on 2020-07-14 19:22

from django.db import migrations
from datetime import datetime
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', 'initial-load-report-data'),
    ]

    def remove_assignee(apps, schema_editor):
        # get all reports
        reports = apps.get_model('cts_forms', 'Report')
        timezone = pytz.timezone("UTC")
        july1 = timezone.localize(datetime(2020, 7, 1))
        for report in reports.objects.all():
            # remove assignee for report closed date is before june 30 2020,
            if report.closed_date is not None:
                print(report.closed_date)
                if report.closed_date < july1:
                    report.assigned_to = None
                    report.save()
    operations = [
        migrations.RunPython(remove_assignee),
    ]
