# Generated by Django 2.2.13 on 2020-07-10 17:31

from django.db import migrations
from datetime import datetime
import pytz
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0083_add_crt_hce_spl_form_letters'),
    ]

    def remove_assignee(apps, schema_editor):
        # get all reports
        reports = apps.get_model('cts_forms', 'Report')

        timezone = pytz.timezone("UTC")
        july1 = datetime(2020, 7, 1)

        timezone.localize(july1)

        for report in reports.objects.all():
            # remove assignee for report closed date is before june 30 2020,
            if report.closed_date is not None:
                print(report.closed_date)
                if report.closed_date < july1:
                    report.assigned_to = None
                    report.save()
    operations = [
        migrations.RunPython(remove_assignee),
    ]
