# Generated by Django 3.2.17 on 2023-04-10 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the feature, using only lowercase letters and dashes (-)', max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[a-z\\-]*$', 'Feature may only contain the letters a-z and the dash (-) character')])),
                ('description', models.TextField(blank=True, help_text="A description of the feature, if the name isn't sufficient to explain what it is.", null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether to show this feature in the application.')),
            ],
        ),
    ]
