# Generated by Django 3.2.17 on 2023-04-10 20:43

from django.db import migrations
from features.models import AddFeatureMigration


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial')
    ]

    operations = [
        AddFeatureMigration('dj-number', True),
    ]
