# Generated by Django 3.2.17 on 2023-05-24 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_dj_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='users_when_disabled',
            field=models.ManyToManyField(blank=True, help_text='Users who are allowed to see this feature. Note that enabled features will be visible to everybody, always.', to=settings.AUTH_USER_MODEL),
        ),
    ]
