# Generated by Django 3.2.17 on 2023-05-24 18:35

from django.db import migrations
from features.models import AddFeatureMigration


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_feature_users_when_disabled'),
    ]

    operations = [
        AddFeatureMigration('team-management-redo', False),
    ]
