# Generated by Django 4.2.2 on 2023-07-14 20:26

from django.db import migrations
from features.models import AddFeatureMigration


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_education_footer'),
    ]

    operations = [
        AddFeatureMigration('separate-referrals-workflow', False,
                            description='Moves the referrals workflow from the contact complainant process to its own modal.'),
    ]
