# Generated by Django 4.2.3 on 2023-11-22 15:29

from django.db import migrations
from features.models import AddFeatureMigration


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_email_responses_card'),
    ]

    operations = [
        AddFeatureMigration(
            'tags',
            False,
            description='Show tags throughout the application'
        ),
    ]
