# Generated by Django 4.2.3 on 2024-02-05 11:40

from django.db import migrations
from features.models import AddFeatureMigration


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_fuzzy_location'),
    ]

    operations = [
        AddFeatureMigration(
            'saved-searches',
            False,
            description='Show saved search features'
        ),
    ]
