# Generated by Django 4.2.3 on 2024-08-30 8:51

from django.db import migrations
from features.models import AddFeatureMigration


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_notification_management'),
    ]

    operations = [
        AddFeatureMigration(
            'resources',
            False,
            description='Show new resources page'
        ),
    ]
