# used by cloud.gov - see: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html
# iptables is necessary because Jupyter needs to make requests to itself for authentication. Without IP tables, its requests get translated into localhost:80 (which is closed).
web: mkdir -p assignments && jupyterhub --ip 0.0.0.0 --port $PORT
