# Generated by Django 5.2.14 on 2026-07-29 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapWidgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name used to identify this map's data. The map widget fetches its data by this name.", max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]+$', 'Name may only contain lowercase letters a-z, digits 0-9, and the dash (-) character.')])),
                ('data', models.JSONField(blank=True, default=dict, help_text='The JSON data for the map')),
            ],
            options={
                'verbose_name': 'Map widget data',
                'verbose_name_plural': 'Map widget data',
            },
        ),
    ]
