# Generated by Django 5.2.14 on 2026-08-17 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsWidgetColumnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name used to identify this news column's data. Data is fetched by this name.", max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]+$', 'Name may only contain lowercase letters a-z, digits 0-9, and the dash (-) character.')])),
                ('data', models.JSONField(blank=True, default=list, help_text='The list of news articles formatted as JSON for a news widget column')),
            ],
            options={
                'verbose_name': 'News widget column',
                'verbose_name_plural': 'News widget columns',
            },
        ),
    ]
