# Generated by Django 5.2.14 on 2026-08-26 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_widget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsWidgetCardsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name used to identify this news card set's data. Data is fetched by this name.", max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]+$', 'Name may only contain lowercase letters a-z, digits 0-9, and the dash (-) character.')])),
                ('data', models.JSONField(blank=True, default=list, help_text='The list of news cards formatted as JSON for a news carousel')),
            ],
            options={
                'verbose_name': 'News widget card set',
                'verbose_name_plural': 'News widget card sets',
            },
        ),
    ]
